Implementing Article List component
rentalutions/marketing pull request #100
Opened 2021-05-25 13:09 UTC by henriquecfreitas

![localhost_4000_info_henrique-test](https://user-images.githubusercontent.com/22528445/119503005-20b8e480-bd30-11eb-88ad-97f486f10188.png)
![localhost_4000_info_henrique-test(iPhone X)](https://user-images.githubusercontent.com/22528445/119503016-244c6b80-bd30-11eb-9a39-8398d96e7a85.png)

2021-05-26 13:46 UTC, pkrawc requested changes

2021-06-15 13:54 UTC, quaardvark requested changes
I was not able to re-create the article list from the home page successfully (cc @pkrawc )

![Screenshot_20210615_164954](https://user-images.githubusercontent.com/1927171/122064770-11dac480-cdfa-11eb-8bf8-075cc3afb7cc.png)

1) Slice is missing description field. Skew?
2) Title should not have a green background. Title should be title and green background text should be an additional field eyebrow or tag
3) Images should have gray backdrop by default. Should also probably incorporate `next/image`
4) There are 2 fields on the slice that say "Background color" - not clear which is which

2021-06-15 17:05 UTC, henriquecfreitas commented
About the SS: I think you only need to set different color for the slice BG and the cards BG's

1. I'll add description and skew fields
2. I'll rename it to `tag`, we aren't handling `title` as a card field because each card can style it's title on it, or don't have title at all
3. Agreed
4. We have a `Background color` field and a `Background color for 'Read More' card` field. I personally think it is clear, considering the limitations we have to create a non repeatable section for the `Read More card`. I'm open for suggestions on that

@quaardvark 
> I was not able to re-create the article list from the home page successfully (cc @pkrawc )
> 
> ![Screenshot_20210615_164954](https://user-images.githubusercontent.com/1927171/122064770-11dac480-cdfa-11eb-8bf8-075cc3afb7cc.png)
> 
> 1. Slice is missing description field. Skew?
> 2. Title should not have a green background. Title should be title and green background text should be an additional field eyebrow or tag
> 3. Images should have gray backdrop by default. Should also probably incorporate `next/image`
> 4. There are 2 fields on the slice that say "Background color" - not clear which is which


@pkrawc 
> * Description as in something to tell the Prismic user how to consume this? Or description as in text under the slice title?
> * That's a tag, not a title. Each article should probably have a title though.
> * Agreed
> * Agreed

2021-06-22 08:39 UTC, quaardvark commented
> About the SS: I think you only need to set different color for the slice BG and the cards BG's.
> And we have a bug on the button for large length labels, I'll work on that.
> 
> 1. I'll add description and skew fields
> 2. I'll rename it to `tag`, we aren't handling `title` as a card field because each card can style it's title on it, or don't have title at all
> 3. Agreed
> 4. We have a `Background color` field and a `Background color for 'Read More' card` field. I personally think it is clear, considering the limitations we have to create a non repeatable section for the `Read More card`. I'm open for suggestions on that
> 

1. :+1: 
2. We should have a title field, - we want a guided experience for editors. Styling can be done with extra labels, and / or, derived from card type. No title should be still possible with dedicated field
3. :+1: 
4. 
![Screenshot_20210622_113149](https://user-images.githubusercontent.com/1927171/122892624-3846b580-d34e-11eb-937f-183c1f877a03.png)

2021-06-22 13:24 UTC, henriquecfreitas commented
> > About the SS: I think you only need to set different color for the slice BG and the cards BG's.
> > And we have a bug on the button for large length labels, I'll work on that.
> > 
> > 1. I'll add description and skew fields
> > 2. I'll rename it to `tag`, we aren't handling `title` as a card field because each card can style it's title on it, or don't have title at all
> > 3. Agreed
> > 4. We have a `Background color` field and a `Background color for 'Read More' card` field. I personally think it is clear, considering the limitations we have to create a non repeatable section for the `Read More card`. I'm open for suggestions on that
> 
> 1. 👍
> 2. We should have a title field, - we want a guided experience for editors. Styling can be done with extra labels, and / or, derived from card type. No title should be still possible with dedicated field
> 3. 👍
> 
> ![Screenshot_20210622_113149](https://user-images.githubusercontent.com/1927171/122892624-3846b580-d34e-11eb-937f-183c1f877a03.png)

We're seeing different labels in prismic...

Renaming `Background color` to `Card background color` its a good suggestion, I'll implement as well as the other labels suggestions.

<img width="729" alt="Screen Shot 2021-06-22 at 8 22 04 AM" src="https://user-images.githubusercontent.com/22528445/122932011-fd835400-d332-11eb-9115-a5d74ceed312.png">

2021-06-22 14:45 UTC, quaardvark commented
@henriquecfreitas I'm looking at the Prismic type from this PR specifically, you can see it matches the names from my screenshot

2021-06-24 15:43 UTC, quaardvark requested changes
FYI storybook for ArticleList is crashing

2021-06-24 15:43 UTC, quaardvark commented on src/components/organisms/ArticleList/article-card.js
> +            <Image
We can't use `next/image` here, - it wouldn't work outside on Next.JS context. We should use `next/image` in Slice and `<img />` in storybooks, just like in all other `next/image` usages in this repo

2021-06-24 15:43 UTC, quaardvark commented on src/types/info.json
> +                  "label" : "Image background color"
Do we really need that? I think we agreed that it should be gray by default

2021-06-24 15:54 UTC, henriquecfreitas commented on src/types/info.json
> +                  "label" : "Image background color"
It is gray by default now.
Giving the user the possibility to opt for another color instead of the default one, for the cases where gray isn't a good fit (eg: if you have the same gray as the bg color for the card)

2021-06-25 13:01 UTC, quaardvark commented on src/types/info.json
> +                  "label" : "Image background color"
Well, it that case shouldn't it be `ui_500`? I think `ui_300` is the default page background, so essentially it will blend with the page in this case?

2021-06-25 13:02 UTC, quaardvark commented on src/types/info.json
> +                  "label" : "Image background color"
Also please group link and image fields together (image first and link last)

2021-06-25 13:33 UTC, quaardvark commented on src/components/organisms/ArticleList/article-card.js
> +          })}
Doesn't title have any default styling for font-size etc?

2021-06-25 13:35 UTC, quaardvark commented on src/types/info.json
> +              },
Should probably be single line headers? I don't see the point of paragraphs, lists and especially embeds

2021-06-25 14:04 UTC, henriquecfreitas commented on src/types/info.json
> +                  "label" : "Image background color"
Yeah, this was a mistake 😬
Already replaced to `ui_500`

2021-06-29 15:29 UTC, quaardvark requested changes

2021-06-29 15:29 UTC, quaardvark commented on src/components/organisms/ArticleList/article-link.js
> +    <NextLink passHref href={Link.href} {...props} />
Abstraction leak, - we should avoid using `next` components in organisms

2021-06-29 15:29 UTC, quaardvark commented on src/components/partials/SliceZone/components/ArticleListSlice/index.js
> +        </Box>
This should be done differently, - default font styling will be applied to the `<Box />` but the defaults in `RichText` for H1...H5 will override that. Please refactor in a way where RichText will be directly passed, w/o a `Box`

2021-06-29 15:29 UTC, quaardvark commented on src/components/organisms/ArticleList/article-card.js
> +  bg,
Should probably default to `ui_100`

2021-06-29 15:29 UTC, quaardvark commented on src/components/organisms/ArticleList/article-list.stories.js
> +    <Box width="100%" py="4rem" background="#F9F9F9">
`F9F9F9` doesn't have enough contrast. `ui_300` is `#f3f3f3`. Should probably use `bg="ui_300"` though

2021-06-29 15:29 UTC, quaardvark commented on src/components/partials/SliceZone/components/ArticleListSlice/index.js
> +  }
Should it still render when all the data is not filled in? Can we provide some sensible defaults in case we really want it to always be there? (cc: @pkrawc )

2021-06-29 15:29 UTC, quaardvark commented on src/components/partials/SliceZone/components/ArticleListSlice/index.js
> +        label: linkLabel,
I'd prefer forming link as an element in the slice instead of this

2021-06-29 15:29 UTC, quaardvark commented on src/components/organisms/ArticleList/index.js
> +              ...STYLING.title,
Default styling should be applied before `sx` in case it would need to be overridden by the caller. Same below with the description

2021-06-29 15:29 UTC, quaardvark commented on src/components/organisms/ArticleList/article-list.stories.js
> +            ),
We probably want to implement titles via separate API, otherwise this story doesn't reflect the slice

2021-07-07 19:19 UTC, quaardvark commented on src/components/partials/SliceZone/components/ArticleListSlice/index.js
> +  }
FYI @pkrawc I implemented a change where read more card is not rendered at all if there's no content

2021-07-07 19:22 UTC, quaardvark commented
@nshonda tagging you for review since you are a stakeholder for this item

2021-07-07 19:22 UTC, quaardvark approved these changes

2021-07-07 21:38 UTC, nshonda approved these changes

2021-07-08 14:27 UTC, merged