Implementing How It Works carousel
rentalutions/marketing pull request #105
Opened 2021-06-03 15:59 UTC by henriquecfreitas

2021-06-09 14:13 UTC, pkrawc requested changes
`src/components/organisms/HowItWorks/carousel/index.js`
Any reason the above isn't just a carousel named file? I think index files everywhere is a code smell.

`src/components/organisms/HowItWorks/slices/index.js`
I don't think we should be relating anything to slices to the organism.

2021-06-09 14:13 UTC, pkrawc commented on src/components/molecules/Slider/index.js
> +import ControlChevron from "components/elements/ControlChevron"
The filename should still be lowercase with a hyphen delineating spaces.

2021-06-09 14:13 UTC, pkrawc commented on src/components/organisms/Testimonials/carousel/testimonials-carousel-item.js
> +  }, [level])
This is a great use of useMemo.

2021-06-09 14:20 UTC, henriquecfreitas commented on src/components/molecules/Carousel/use-carousel.js
> +  const { item: activeItem } = useMemo(visibleItem, [visibleItem])
`visibleItem` callback will be memorized, but I think that without wrapping its execution inside the `useMemo` it will be reexecuted on every render (but I might be wrong)

Taking a second look on the code now, I think that `activeItem` and `visibleItems` can be both defined on the same `useMemo`, having `visibleItem` declared as function inside the callback func, since it is not being exported

2021-06-11 14:19 UTC, pkrawc commented on src/components/molecules/Slider/index.js
> +import ControlChevron from "components/elements/ControlChevron"
file and folder names should use the same convention

2021-06-15 14:01 UTC, quaardvark commented
@henriquecfreitas build is failing FYI

2021-06-22 22:01 UTC, pkrawc commented
Looks like this build is still failing @henriquecfreitas

2021-06-22 22:02 UTC, pkrawc requested changes
Looks like the build is still failing, could we address that?

Mostly the changes I was asking for are code convention and cleanliness, so this is close to done IMO.

2021-06-25 12:57 UTC, quaardvark requested changes
I tried to check `Carousel` in Storybook but couldn't figure out what it supposed to do. Can you check if it needs changes per this PR? Or what is it supposed to be?

2021-06-25 12:57 UTC, quaardvark commented on src/components/molecules/Carousel/use-carousel.js
> +            console.log(currentItem.level !== 0, currentItem)
Forgotten hacks

2021-06-25 12:57 UTC, quaardvark commented on src/components/molecules/Carousel/use-carousel.js
> +  const { activeItem, visibleItems } = useMemo(
I think `useMemo` is not the right approach here, since it will be recalculated on every click/transition anyway. I think we maybe want to put it in `useCallback` and pass `activeIndex` as argument instead of taking in from the scope. This way it will be very stable

2021-06-25 12:57 UTC, quaardvark commented on src/components/molecules/Carousel/use-carousel.js
> +  const visibleItem = useCallback(
Let's name functions a bit more appropriately, this looks like a prop/variable. `getVisibleItem` is probably clearer

2021-07-12 17:02 UTC, nshonda approved these changes

2021-07-12 17:03 UTC, nshonda commented
@quaardvark we'll have some conflict when merging pages/main in here after the how it works skew changes

2021-08-25 15:23 UTC, closed without merging