Implementing realtor and houselogic badges on footer
rentalutions/marketing pull request #108
Opened 2021-06-07 22:26 UTC by henriquecfreitas

2021-06-09 14:18 UTC, pkrawc approved these changes
Looks good to me. Didn't run a local version but from a code perspective, this is top-notch.

2021-06-09 14:27 UTC, quaardvark requested changes

2021-06-09 14:27 UTC, quaardvark commented on src/components/partials/AvailFooter/index.js
> +              <img alt="Realtor.com" src="/realtor_badge.svg" />
We should use `next/image` for images from now on

2021-06-10 12:27 UTC, quaardvark approved these changes

2021-06-10 12:27 UTC, merged