Fix/pricing card updates
rentalutions/marketing pull request #113
Opened 2021-06-10 19:46 UTC by nshonda

- left-aligned text fixes
- removed shadow from cards except the primary one
- added special offer field/tag

2021-06-11 14:17 UTC, quaardvark requested changes

2021-06-11 14:17 UTC, quaardvark commented on src/components/organisms/PlansPrices/plan-card.js
> +      </div>}
1. We should use `<Box />` instead of `<div />` and `sx` prop instead of `style`.
2. "Special offer" text should be customizable.
3. Please use ESLint and Prettier, because this code is wrongly formatted.

2021-06-11 14:17 UTC, quaardvark commented on src/components/organisms/PlansPrices/plans-prices.stories.js
> +    specialOffer: true,
Should probably be a rich text element

2021-06-11 14:17 UTC, quaardvark commented on src/components/organisms/PlansPrices/index.js
> +                shadow={index === 0 ? true : false}
Not sure if this is the right approach. I think the implication from design was that the "primary" card was the one with the "special offer" tag

2021-06-14 13:50 UTC, quaardvark requested changes
This has failed to compile, please keep an eye on that

2021-06-14 13:50 UTC, quaardvark commented on src/components/organisms/PlansPrices/index.js
> +                shadow={plan.specialOffer}
This will always be an object from Prismic, so always true

2021-06-14 13:50 UTC, quaardvark commented on src/components/organisms/PlansPrices/index.js
> +        maxWidth: ["unset", "unset", "75%", "75%", "54rem"],
I still don't see where this comes from. 75% seems arbitrary to me

2021-06-14 13:50 UTC, quaardvark commented on src/components/organisms/PlansPrices/plan-card.js
> +            sx={{ fontSize: "14px" }}
Should be 1.1667rem

2021-06-14 13:50 UTC, quaardvark commented on src/components/organisms/PlansPrices/index.js
> +                    ...STYLING.headline,
I think this is slipped from the original implementation. Pretty sure `sx` should be last here in order for labels to be able to override the default styling. Same with the `subtitle`

2021-06-14 13:50 UTC, quaardvark commented on src/components/partials/SliceZone/components/PlansPricesSlice/index.js
> +      specialOffer: specialOffer.length > 0 && (
Can (very likely) also contain an empty string so an array length be 1, but no text. If you need to check use `specialOffer?.[0]?.text`

2021-06-14 14:11 UTC, nshonda commented on src/components/organisms/PlansPrices/index.js
> +        maxWidth: ["unset", "unset", "75%", "75%", "54rem"],
is the same configurations from the PlansGrid, I just copied from there @quaardvark

2021-06-14 15:45 UTC, nshonda commented on src/components/organisms/PlansPrices/index.js
> +                shadow={plan.specialOffer}
this check if the object is set, so it throws true or false depending on it and adds the shadow css
<img width="856" alt="Screen Shot 2021-06-14 at 12 43 47" src="https://user-images.githubusercontent.com/2747573/121920402-63a62080-cd0e-11eb-9971-6a43035b1357.png">

2021-06-14 18:36 UTC, quaardvark commented on src/components/partials/SliceZone/components/PlansPricesSlice/index.js
> +      specialOffer: specialOffer && specialOffer?.[0]?.text && (
FYI, you don't need to do `specialOffer && specialOffer...` here, optional chaining takes care of that - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2021-06-14 18:40 UTC, quaardvark commented on src/components/organisms/PlansPrices/index.js
> +        maxWidth: ["unset", "unset", "75%", "75%", "54rem"],
I think in this case we need to wrap both of them into the same container if possible. Not a good idea to keep two implementation of the same box, basically. Unless I'm missing something

2021-06-14 18:44 UTC, quaardvark commented on src/components/organisms/PlansPrices/index.js
> +                shadow={plan.specialOffer}
With the change in the slice - yes. I would coerce it to boolean for the clarity of intention

2021-06-14 20:28 UTC, nshonda commented on src/components/organisms/PlansPrices/index.js
> +        maxWidth: ["unset", "unset", "75%", "75%", "54rem"],
we need a separate box, otherwise, the text doesn't align correctly when we have horizontally stacked cards
below examples are using the plans grid
<img width="894" alt="Screen Shot 2021-06-14 at 16 32 57" src="https://user-images.githubusercontent.com/2747573/121948982-539e3900-cd2e-11eb-947d-a1291ed1a67a.png">

<img width="924" alt="Screen Shot 2021-06-14 at 16 33 38" src="https://user-images.githubusercontent.com/2747573/121948971-513bdf00-cd2e-11eb-901b-132767422cde.png">

and here are using the custom text grid

<img width="944" alt="Screen Shot 2021-06-14 at 16 36 03" src="https://user-images.githubusercontent.com/2747573/121949253-a1b33c80-cd2e-11eb-9958-a3fd925dce0b.png">
<img width="888" alt="Screen Shot 2021-06-14 at 16 35 23" src="https://user-images.githubusercontent.com/2747573/121949265-a4ae2d00-cd2e-11eb-88ce-b8015db96926.png">

2021-06-15 12:27 UTC, quaardvark commented on src/components/organisms/PlansPrices/index.js
> +        maxWidth: ["unset", "unset", "75%", "75%", "54rem"],
@nshonda please implement a solution with a single box for sizing the container, refactor as much as needed. The flaw of current approach is very visible in a Storybook:

![Screenshot_20210615_151749](https://user-images.githubusercontent.com/1927171/122051441-46944f00-cded-11eb-94f7-30d5d06f2297.png)

Or on the tablet:
![Screenshot_20210615_152551](https://user-images.githubusercontent.com/1927171/122052148-097c8c80-cdee-11eb-9aa1-1946e77f8f3f.png)


Also, Figma has a max width of 54rem for both variants, so I really don't see where 75% or 61rem are coming from. There should be 2 sizes - 100% for screens where 2 horizontally stacked cards don't fit and 54rem for the rest.

If you have questions please reach out to me in Slack.

2021-06-15 12:29 UTC, quaardvark commented on src/components/organisms/PlansPrices/index.js
> +                shadow={plan.specialOffer}
`shadow={!!plan.specialOffer}`

2021-06-15 12:53 UTC, quaardvark commented on src/components/organisms/PlansPrices/plan-card.js
> +            sx={{ fontSize: "14px" }}
This is not resolved, we should not use `px` anywhere

2021-06-15 12:59 UTC, quaardvark commented on src/components/organisms/PlansPrices/plan-card.js
> +            mr="1.1667rem"
This was 1rem, my comment about 1.1667rem was concerning the font size. I don't see a reason this element needs right margin.

2021-06-16 13:46 UTC, quaardvark commented on src/components/organisms/PlansPrices/index.js
> +        maxWidth: ["unset", "unset", "75%", "75%", "54rem"],
This is not resolved. Still major issues with layout
![Screenshot_20210616_164005](https://user-images.githubusercontent.com/1927171/122230453-59c51e80-cec2-11eb-8e75-28fe758e1b48.png)

Please implement a single sizing box, not 3 grids.

2021-06-17 13:10 UTC, quaardvark commented
@nshonda Still experiencing major issues with the layout

1) The text is not aligned with the pricing cards on vertical stacking
![Screenshot_20210617_160531](https://user-images.githubusercontent.com/1927171/122402348-116f3480-cf86-11eb-9ffa-787897c81c80.png)

2) Horizontally stacked is not centered on the page
![Screenshot_20210617_160547](https://user-images.githubusercontent.com/1927171/122402577-47141d80-cf86-11eb-9342-882b44a00d22.png)

Let's connect tomorrow before the stand to try to resolve this properly

2021-06-18 15:59 UTC, quaardvark approved these changes

2021-06-18 16:00 UTC, merged