Feat/how it works skew
rentalutions/marketing pull request #126
Opened 2021-06-24 22:27 UTC by nshonda

As seen on Home:

Skew should wrap individual sections instead of whole slice
Add alternating background color feature

2021-06-25 12:44 UTC, quaardvark requested changes

2021-06-25 12:44 UTC, quaardvark commented on src/components/organisms/HowItWorks/index.js
> +  if (alternateBackground) {
Is it possible to do it without so much code duplication? What makes alternateBackground so different?

2021-06-25 12:44 UTC, quaardvark commented on src/types/info.json
> +                  "label" : "Alternate background color? (will start with the color set on background color setting)"
Good label :+1:

2021-06-25 12:44 UTC, quaardvark commented on src/components/organisms/HowItWorks/index.js
> +        skew="left"
Should probably expose it as param and add it to Prismic as well instead of hardcoding left

2021-06-25 12:44 UTC, quaardvark commented on src/components/organisms/HowItWorks/index.js
> +        bg={background === "blue_500" ? "transparent" : "blue_500"}
Is `blue_500` the only option for background? If yes, we should add more.

2021-06-25 12:44 UTC, quaardvark commented on src/components/organisms/HowItWorks/index.js
> +      <Container sx={{ maxWidth: "none" }}>
Should probably move it lower down the stack instead of doing this. I suggest to try `<Container as={Grid} ... />` or vice versa in each section and change this one to a box instead

2021-06-25 12:44 UTC, quaardvark commented on src/components/organisms/HowItWorks/index.js
> +        as={motion.aside}
This is useless without `animation.{item|container}` props. I think `{...animation?.container}` should move from grid here

2021-06-25 20:09 UTC, nshonda commented on src/components/organisms/HowItWorks/index.js
> +        bg={background === "blue_500" ? "transparent" : "blue_500"}
right now it's either transparent or blue_500, so we just alternate between those two, if we add more we'll probably need to add a second field when having alternating backgrounds I think

2021-06-25 20:31 UTC, nshonda commented on src/components/organisms/HowItWorks/index.js
> +      <Container sx={{ maxWidth: "none" }}>
I replaced this for a box instead

2021-06-29 16:15 UTC, quaardvark commented on src/components/organisms/HowItWorks/index.js
> +        bg={background === "blue_500" ? "transparent" : "blue_500"}
This is not resolved, I don't see this change implemented.

We should alternate between specified background and transparent.

2021-06-29 16:47 UTC, quaardvark requested changes
Please implement customizable background options (all the default colors we currently use elewhere). I'm not commenting on code flaws there because I expect the to be weeded out during this refactor.

We are implementing it for the Homepage, which alternates between `blue_100` and `transparent`.

2021-07-05 14:10 UTC, quaardvark requested changes
As per previously discussed guidelines, please fix the storybook. Currently it does not reflect what we are trying to achieve.

1) Add a story with alternating backgrounds
2) Fix the "With Flip" story with strange colors
3) Fix the container width issue so that 

Additionally, please fix the regression on the page https://info.avail.co/info/product-referral-program-login (http://localhost:4000/info/product-referral-program-login)

![image](https://user-images.githubusercontent.com/1927171/124484300-f0934580-ddb3-11eb-8888-01939562ac23.png)

2021-07-05 14:10 UTC, quaardvark commented on src/components/organisms/HowItWorks/index.js
> +          color={isDark ? "blue_100" : "inherit"}
We probably want `ui_100` here until theming arrives

2021-07-05 14:10 UTC, quaardvark commented on src/components/organisms/HowItWorks/index.js
> +            background={background === "transparent" ? null : background}
`background: transparent` is a valid value, should be no need for `null` here

2021-07-05 14:10 UTC, quaardvark commented on src/components/organisms/HowItWorks/index.js
> +        <SkewBox
I'm not sure we need SkewBox here, since the children are also wrapped in it. What does this achieve with `skew=none`

2021-07-06 14:39 UTC, quaardvark requested changes
The header is still not in the right place
![Screenshot_20210706_172324](https://user-images.githubusercontent.com/1927171/124619062-fc007280-de80-11eb-959e-fb989b6ee760.png)

Should align with the rest of the components on the page

2021-07-06 15:04 UTC, quaardvark requested changes
Still doesn't align on 1920px screen

![image](https://user-images.githubusercontent.com/1927171/124623175-6b2b9600-de84-11eb-8920-7f68e36699e7.png)

2021-07-06 15:04 UTC, quaardvark commented on src/components/organisms/HowItWorks/index.js
> +              maxWidth: ["62rem", "62rem", "62rem", "80rem", "100rem"],
This breaks the organism abstraction. We should use the `containerWidth` value passed from the slice here

2021-07-06 15:13 UTC, quaardvark commented on src/components/organisms/HowItWorks/index.js
> +              maxWidth: ["62rem", "62rem", "62rem", "80rem", "100rem"],
@nshonda 

There's some serious issues with the header layout. It looks like it's not centered on the page, but it centers it's content intsead

![image](https://user-images.githubusercontent.com/1927171/124624605-b2665680-de85-11eb-9393-789168108245.png)

I'd suggest to use `Container` with `containerWidth` - should align fine

2021-07-06 16:56 UTC, quaardvark approved these changes

2021-07-06 16:56 UTC, merged