Created the Whats In A organism
rentalutions/marketing pull request #139
Opened 2021-07-23 14:16 UTC by taylorsavegnago

Result: 
![image](https://user-images.githubusercontent.com/18465425/126794516-5b1bbcbf-961e-4160-bf16-309bd36b2762.png)

2021-07-23 19:09 UTC, taylorsavegnago commented
The effect developed is not 100% equals to the layout because the keyframes existents doesn't match, for this reason I needed to do some adjustments

2021-07-26 14:51 UTC, quaardvark requested changes
Styling looks broken on tablet
![Screenshot_20210726_173324](https://user-images.githubusercontent.com/1927171/127009401-aca7f154-e646-4fb7-a026-c4be4a40fc0c.png)

and on the mobile
![Screenshot_20210726_174944](https://user-images.githubusercontent.com/1927171/127009597-7ed17f87-7084-4088-bc34-9ef60c81e28f.png)

Code formatting also doesn't look good, - please use ESLint and Prettier, - they report 77 issues
![Screenshot_20210726_175129](https://user-images.githubusercontent.com/1927171/127009869-2f0798a7-ba65-4d9f-8427-7c1d1a4dbe9d.png)

2021-07-26 14:51 UTC, quaardvark commented on src/components/organisms/WhatsInA/whats-in-a.stories.js
> +]
I think we should combine these arrays into one, something like 
```
{ 
    number: "6",
    location : {
        left: "65%",
        top: "90%",
    },
    title: "Disclosures in lease",
    text: "Besides attaching require disclosure pamphlets, the lease includes all required disclosure language directly within the lease.",
},
```

2021-07-26 14:51 UTC, quaardvark commented on src/components/organisms/WhatsInA/index.js
> +  line-height: 27px;
We should try to avoid duplicating properties, - ideally these should be derived from the same base styled component

2021-07-26 14:51 UTC, quaardvark commented on src/components/organisms/WhatsInA/index.js
> +                      lineHeight: '27px'
All `px` and `em` sizes should be converted to `rem`. Probably should round them up for convenience as well

2021-07-26 14:51 UTC, quaardvark commented on src/components/organisms/WhatsInA/index.js
> +  animation-iteration-count: infinite;
Can we do this with `sx` somehow?

2021-07-26 14:51 UTC, quaardvark commented on src/components/organisms/WhatsInA/whats-in-a.stories.js
> +      description={<Text as="h5" color="blue_700">What's In A Description</Text>}
Top :+1:

2021-07-30 15:23 UTC, quaardvark approved these changes

2021-07-30 15:27 UTC, merged