credit boost page qa changes
rentalutions/marketing pull request #163
Opened 2021-08-31 22:25 UTC by nshonda

https://airtable.com/tblXKaz8x2gdERalp/viwuGoo8g6PEIozUb/recf5nqCMlU8vv7eP?blocks=hide

https://marketing-git-pages-main-rent-avail.vercel.app/tenants/report-my-rent

2021-09-08 14:56 UTC, quaardvark commented
@nshonda Is this ready for review?

2021-09-08 15:11 UTC, nshonda commented
@quaardvark  yup, ready for review

2021-09-09 16:57 UTC, quaardvark requested changes

2021-09-09 16:57 UTC, quaardvark commented on src/components/organisms/Hero/index.js
> +      sx={{ textAlign: "center", display: ["none", "block"] }}
I think this can potentially negatively affect existing pages that did show image on the mobile. What is the purpose of this change?

2021-09-09 16:57 UTC, quaardvark commented on src/components/organisms/Testimonials/cards/index.js
> +            testimonials?.map(
That's a lot of code duplication. Also, I think we should try to center it when they don't take all available space - including where there's 2 cards

2021-09-09 16:57 UTC, quaardvark commented on src/components/partials/SliceZone/components/HowItWorksSlice/index.js
> +  }
We should use `sx` for this

2021-09-09 16:57 UTC, quaardvark commented on src/components/partials/SliceZone/components/PitchCardsSlice/index.js
> +        m={["4rem auto", "6rem auto 12rem"]}
Is this for centering? I think we decided that centered pitch cards would be a variant

2021-09-09 16:57 UTC, quaardvark commented on src/components/static/StaticCreditBoostTable/index.js
>    }
Should be in `sx`

2021-09-09 17:54 UTC, nshonda commented on src/components/organisms/Hero/index.js
> +      sx={{ textAlign: "center", display: ["none", "block"] }}
this was a request from vini here: https://www.figma.com/file/YcZAAqtHklQTUQQQWbhNED/Marketing-Pages-Spec?node-id=1%3A1110 and here https://www.figma.com/file/YcZAAqtHklQTUQQQWbhNED/Marketing-Pages-Spec?node-id=37%3A1704

2021-09-09 18:01 UTC, nshonda commented on src/components/partials/SliceZone/components/HowItWorksSlice/index.js
> +  }
I tried to do that, but this seems like an issue with next Image not working properly, this fix is for this page in specific: https://marketing-git-pages-main-rent-avail.vercel.app/landlords/rent-analysis the img in here is not following the intrisic layout set on the rich text component, I'm not sure if this is a miss configuration from next or some other issue @quaardvark

2021-09-09 18:03 UTC, nshonda commented on src/components/partials/SliceZone/components/PitchCardsSlice/index.js
> +        m={["4rem auto", "6rem auto 12rem"]}
no this is for the whole section

2021-09-10 14:08 UTC, quaardvark requested changes

2021-09-10 14:08 UTC, quaardvark commented on src/components/organisms/Hero/index.js
> +      sx={{ textAlign: "center", display: ["none", "block"] }}
I understand, but this is not solving it properly and breaks the production pages. This is what should happen:

1. Clarify the requirements, - if it's OK that the image will be not displayed on mobile, including paid search media pages. Marketing should also be involved in this discussion
2. Implement a solution based on the above:
- If the image removal affects only these pages: Introduce a new parameter to Prismic model
- If the image removal affects all pages: Lease as is

2021-09-10 14:08 UTC, quaardvark commented on src/components/organisms/Testimonials/cards/index.js
> +            testimonials?.map(
Not resolved

2021-09-10 14:08 UTC, quaardvark commented on src/components/partials/SliceZone/components/HowItWorksSlice/index.js
> +  }
Do you mean that `<HowItWorks sx={{ "& .block-img": { img: { maxWidth: "100%" } }  } }` is not working?

2021-09-10 14:08 UTC, quaardvark commented on src/components/partials/SliceZone/components/PitchCardsSlice/index.js
> +        m={["4rem auto", "6rem auto 12rem"]}
Why would we need to center it? Do we have PitchCards with less than 3 cards?

2021-09-10 14:08 UTC, quaardvark commented on src/components/static/StaticCreditBoostTable/index.js
>    }
Not resolved - we shouldn't use hex color values, - take em from the theme with `sx`

2021-09-10 15:11 UTC, nshonda commented on src/components/partials/SliceZone/components/HowItWorksSlice/index.js
> +  }
oh, I thought you meant something else, I'll adjust

2021-09-10 15:24 UTC, nshonda commented on src/components/partials/SliceZone/components/PitchCardsSlice/index.js
> +        m={["4rem auto", "6rem auto 12rem"]}
we already have margin-left and margin-right set as auto on the pitch cards section, but since I'm using breakpoints if I use 0 it overrides those and it sets margin-left and margin-right to 0, so I need to reinforce the auto here

2021-09-10 15:26 UTC, nshonda commented on src/components/partials/SliceZone/components/PitchCardsSlice/index.js
> +        m={["4rem auto", "6rem auto 12rem"]}
![2021-09-10_12-25](https://user-images.githubusercontent.com/2747573/132878365-59e83ece-c95c-4f25-a828-669be173b43f.png)

2021-09-14 11:28 UTC, quaardvark commented on src/components/static/StaticCreditBoostTable/index.js
> +                },
Can't we use styled-system for this? `display: ["none", "initial"]`?

2021-09-14 11:28 UTC, quaardvark commented on src/components/partials/SliceZone/components/PitchCardsSlice/index.js
> +        m={["4rem auto", "6rem auto 12rem"]}
OK, i guess that's fair

2021-09-14 11:28 UTC, quaardvark commented on src/components/organisms/Hero/index.js
> +      sx={{ textAlign: "center", display: ["none", "block"] }}
Any updates on this?

2021-09-14 15:55 UTC, nshonda commented on src/components/organisms/Hero/index.js
> +      sx={{ textAlign: "center", display: ["none", "block"] }}
yes, I added a new field on prismic model for it and made the adjustments to the organism accordingly

2021-09-14 16:09 UTC, quaardvark commented on src/components/organisms/Hero/index.js
> +      sx={{ textAlign: "center", display: ["none", "block"] }}
Cool, thanks for resolving this

2021-09-14 17:51 UTC, quaardvark commented
@nshonda can you link the issues this covers?

2021-09-14 20:16 UTC, nshonda commented
@quaardvark done

2021-09-15 16:44 UTC, quaardvark commented on src/components/partials/SliceZone/components/HowItWorksSlice/index.js
> +            color="inherit"
This looks like a hack of a hack to me. Can you add TODO here for me to take a look at it later? Thanks

2021-09-15 16:44 UTC, quaardvark approved these changes

2021-09-16 15:07 UTC, quaardvark requested changes

2021-09-16 15:07 UTC, quaardvark commented on src/components/partials/SliceZone/components/CallToActionWithEmailCaptureSlice/index.js
> +              sx={{ ...STYLING.hero, fontWeight: "regular" }}
This doesn't match design spec

2021-09-16 15:07 UTC, quaardvark commented on src/components/partials/SliceZone/components/CallToActionWithEmailCaptureSlice/index.js
> +            <RichText render={description} sx={{ ...STYLING.title }} />
Doesn't match design spec

2021-09-16 18:39 UTC, quaardvark commented on src/components/partials/SliceZone/components/RichText/html-serializer.js
> +            color: "blue_900",
@nshonda this should be done on component level as well, because a title can also be paragraph. I will do this

2021-09-16 18:40 UTC, merged