Changes requested
rentalutions/marketing pull request #171
Opened 2021-09-09 20:41 UTC by taylorsavegnago

QA Review

List:

https://airtable.com/appsEN1RgrUk3oyon/tbluJ0kJjMnu1rtsx/viw9dl4sT7CdFVqvO/rec8JWuL3BcvBQY6c?blocks=hide
https://airtable.com/appsEN1RgrUk3oyon/tbluJ0kJjMnu1rtsx/viw9dl4sT7CdFVqvO/recsxTOZFLuVstwsJ?blocks=hide
https://airtable.com/appsEN1RgrUk3oyon/tbluJ0kJjMnu1rtsx/viw9dl4sT7CdFVqvO/rec3TGE4Kys6p2mhI?blocks=hide

I also fixed the color on testimonials title

2021-09-10 13:55 UTC, quaardvark requested changes

2021-09-10 13:55 UTC, quaardvark commented on pages/tenants/digital-leasing/data/testimonials.js
> +            type: "heading1",
Should be H2 probably

2021-09-10 13:55 UTC, quaardvark commented on pages/tenants/online-rent-payments/data/testimonials.js
> +        type: "heading1",
Should probably be H2

2021-09-13 17:14 UTC, taylorsavegnago commented on pages/tenants/online-rent-payments/data/testimonials.js
> +        type: "heading1",
Done

2021-09-13 17:14 UTC, taylorsavegnago commented on pages/tenants/digital-leasing/data/testimonials.js
> +            type: "heading1",
Done

2021-09-14 11:29 UTC, quaardvark commented
@taylorsavegnago could you make sure the build succeeds (you can test locally with `yarn build`) and resolve the conflict?

2021-09-14 14:51 UTC, taylorsavegnago commented
> @taylorsavegnago could you make sure the build succeeds (you can test locally with `yarn build`) and resolve the conflict?

Refactored the codes according to eslint

2021-09-14 16:06 UTC, quaardvark requested changes

2021-09-14 16:06 UTC, quaardvark commented on pages/tenants/online-rent-payments/data/how-it-works.js
> +        alt: null,
I don't see anywhere in the tickets that we need to remove alt texts

2021-09-14 16:06 UTC, quaardvark commented on src/components/organisms/Testimonials/cards/index.js
> +              sx: { ...STYLING.headline, ...title?.props?.sx, color },
I think color props in Testimonials relates to the color of the text on the card, not to the title color

2021-09-14 16:06 UTC, quaardvark commented on pages/tenants/digital-leasing/data/hero.js
> +        type: "heading4",
This should be a paragraph

2021-09-14 18:08 UTC, taylorsavegnago commented on src/components/organisms/Testimonials/cards/index.js
> +              sx: { ...STYLING.headline, ...title?.props?.sx, color },
![image](https://user-images.githubusercontent.com/18465425/133310162-b20f9106-dda5-490d-afff-606785549503.png)
![image](https://user-images.githubusercontent.com/18465425/133310205-5554e103-104e-4901-8162-9d9d75667faf.png)

@quaardvark check that we don't have a text on this card. Do you want I to change the prop to color_title? In my opinion, it is not needed. 

![image](https://user-images.githubusercontent.com/18465425/133310604-d1101562-9c66-4dff-a957-9bbd2abf3c35.png)
In addition, we have some props that are not used in the card, right?

2021-09-14 18:12 UTC, taylorsavegnago commented on pages/tenants/digital-leasing/data/hero.js
> +        type: "heading4",
Changed

2021-09-14 18:13 UTC, taylorsavegnago commented on pages/tenants/online-rent-payments/data/how-it-works.js
> +        alt: null,
It happened when I fixed the conflicts, my mistake. Fixed.

2021-09-15 13:39 UTC, quaardvark commented on src/components/organisms/Testimonials/cards/index.js
> +              sx: { ...STYLING.headline, ...title?.props?.sx, color },
I think we can use an analyze color util to check if the background is dark

2021-09-15 17:48 UTC, taylorsavegnago commented on src/components/organisms/Testimonials/cards/index.js
> +              sx: { ...STYLING.headline, ...title?.props?.sx, color },
If the background is dark, the title will be white or else will be gray

2021-09-15 18:38 UTC, quaardvark approved these changes

2021-09-15 18:39 UTC, merged