adding benefits variants
rentalutions/marketing pull request #178
Opened 2021-09-14 21:13 UTC by nshonda

Adding a variant to pitch cards so content gets centered
related issue:
- https://airtable.com/appsEN1RgrUk3oyon/tbluJ0kJjMnu1rtsx/viwEjc1BEgM0pj72s/recQJIn1jnDLSZR3I?blocks=hide

2021-09-15 13:34 UTC, quaardvark requested changes
I think we should add a select here with a `variant` key instead of a bool. We should also treat the other "button" variant the same way, so PitchCard api would look like `<PitchCard variant={"button" | "benefits"} />`

2021-09-15 16:50 UTC, quaardvark requested changes
`variant` should a slice property, not each invidual pitch card

2021-09-15 17:33 UTC, quaardvark commented on src/components/partials/SliceZone/components/PitchCardsSlice/index.js
> +          {variant === "button" ? (
This should also work with the old API, but maybe I missed where it's stubbed

2021-09-15 19:55 UTC, nshonda commented
@quaardvark do you think we'll have issues with the old API if we make `variant` be a slice property since `linkAsButton` was a card property?

2021-09-16 17:39 UTC, quaardvark commented
@nshonda All I ask is to hoist variant to top and implement this `const isButtonVariant = variant === "button" || linkAsButton`. We'll sort the API thing later, there's probably only a few pages that use it

2021-09-24 21:15 UTC, quaardvark commented
Closing in favor of #196

2021-09-24 21:15 UTC, closed without merging