Fix menu issues
rentalutions/marketing pull request #188
Opened 2021-09-17 16:13 UTC by nshonda

Issue related:
- https://airtable.com/appsEN1RgrUk3oyon/tbluJ0kJjMnu1rtsx/viwEjc1BEgM0pj72s/recFjvYCg7woohk0o?blocks=hide

I'm still working on a way to make the responsive switch better, but for now, I went with the simple solution to switch to hamburger as soon as it doesn't fit.

2021-09-20 17:50 UTC, quaardvark requested changes
Menu visuals do not match design spec

2021-09-20 17:50 UTC, quaardvark commented on src/components/organisms/NewNavBar/AvailRdcNewNavBar/index.js
> +import { AVAIL_BASE_URL, REALTOR_BASE_URL } from "utils/env"
Should not be part of the organism

2021-09-20 19:37 UTC, quaardvark requested changes
Design changes required (not a complete list, please double-check):
- Chevrons are bigger on design
- Menu dropdown - too much space on the top
- Menu dropdown - Closing symbol should be an icon, not a letter "X"
- Menu dropdown - hover should not result in resize of the menu
- Menu dropdown - Online Rent Collection link is too close to the tag
- Mobile menu - Closing symbol should be an icon, not a letter "X"
- Mobile menu - "Sign up" button is missing an icon

2021-09-20 19:37 UTC, quaardvark commented on src/components/organisms/NewNavBar/AvailRdcNewNavBar/index.js
> +                bg="green_500"
color should be `ui_900`. Hover styling is probably wrong too (please advise with Vinnie)

2021-09-21 08:07 UTC, quaardvark requested changes
![Screenshot_20210921_105525](https://user-images.githubusercontent.com/1927171/134135132-bced8e37-4209-47dc-80b8-36a70b67179d.png)
![Screenshot_20210921_105340](https://user-images.githubusercontent.com/1927171/134135136-07dc3457-a8f3-4904-8899-16b13adf9f19.png)
![Screenshot_20210921_104827](https://user-images.githubusercontent.com/1927171/134135137-e641d76b-510b-466f-9ac7-2c7e87231b17.png)

2021-09-22 12:53 UTC, quaardvark requested changes
Please align the sizing, the coloring and other styling with the design spec (on the right):
![Screenshot_20210922_154257](https://user-images.githubusercontent.com/1927171/134346518-8b9be3e0-e2a8-490b-83ba-63dfd554831e.png)

The logos should be properly aligned on bigger screens (as per design spec):
![marketing-git-fix-menu-issues-rent-avail vercel app_](https://user-images.githubusercontent.com/1927171/134346924-84acd7fa-c567-4706-8d72-262ec5aad1c6.png)

2021-09-27 16:50 UTC, quaardvark requested changes

2021-09-27 16:50 UTC, quaardvark commented on src/components/organisms/NewNavBar/AvailRdcNewNavBar/menu-mobile.js
> +            zIndex: "9999",
We should avoid using `zIndex` here

2021-09-27 16:50 UTC, quaardvark commented on src/components/organisms/NewNavBar/AvailRdcNewNavBar/menu-mobile.js
> +                <CustomLink {...primaryLinkProps} style={{ color: "#50E3C2" }}>
Color should be taken from theme as `blue_..`

2021-09-27 16:50 UTC, quaardvark commented on src/components/organisms/NewNavBar/AvailRdcNewNavBar/menu-mobile.js
> +          mt={"-1rem"}
Should avoid negative margins, they don't work in all browsers

2021-09-27 16:50 UTC, quaardvark commented on src/components/partials/NewPageNavBar/index.js
> +          width={144}
We should opt for `layout="fixed"` on both images.

2021-09-27 16:50 UTC, quaardvark commented on src/components/organisms/NewNavBar/AvailRdcNewNavBar/index.js
> +  width: 28rem;
Can we do `maxWidth` instead?

2021-09-27 16:50 UTC, quaardvark commented on src/components/organisms/NewNavBar/AvailRdcNewNavBar/index.js
> +                ]}
We should implement the proper `hover` state for `green_500`, preferably through the variants API. Did we talk with Vinnie on the hover state specs?

2021-09-27 16:50 UTC, quaardvark commented on src/components/organisms/NewNavBar/AvailRdcNewNavBar/index.js
> +            justifyContent: "space-evenly",
I think we should not rely on flex magic here. Logos should be flex: 0, static sized and static paddings.

2021-09-27 16:50 UTC, quaardvark commented on src/components/organisms/NewNavBar/AvailRdcNewNavBar/index.js
> +            sx={{ width: ["87px", "131px"], height: ["2rem", "3rem"] }}
We should move this logic to `layout=static` on Images definition

2021-09-27 16:50 UTC, quaardvark commented on public/rdc-logo.svg
> +<svg width="144" height="36" viewBox="0 0 144 36" fill="none" xmlns="http://www.w3.org/2000/svg">
This SVG has a black outline that should be fixed. I let Vinnie know about this, since this how Figma exports it. Please contact him and replace this logo with a clean version

2021-09-27 20:57 UTC, nshonda commented on src/components/partials/NewPageNavBar/index.js
> +          width={144}
tried that, but ran into some issues on small screens

![image](https://user-images.githubusercontent.com/2747573/134984153-7dfe9108-6024-45bd-b6bd-461beafb3a1d.png)

2021-09-27 20:58 UTC, nshonda commented on src/components/organisms/NewNavBar/AvailRdcNewNavBar/index.js
> +            sx={{ width: ["87px", "131px"], height: ["2rem", "3rem"] }}
check my comment on the layout fixed above

2021-09-28 10:42 UTC, quaardvark requested changes
Component doesn't match the design spec (top: design spec, bottom: this PR)
![Screenshot_20210928_134135](https://user-images.githubusercontent.com/1927171/135072424-860f8d23-ff2d-4b1a-b433-88b25b6637e7.png)

2021-09-28 10:42 UTC, quaardvark commented on src/components/organisms/NewNavBar/AvailRdcNewNavBar/menu-mobile.js
> +          mt={"-1rem"}
This was not resolved

2021-09-28 10:42 UTC, quaardvark commented on src/components/organisms/NewNavBar/AvailRdcNewNavBar/menu-mobile.js
> +                </CustomLink>{" "}
We shouldn't have any space literals in these buttons

2021-09-28 10:42 UTC, quaardvark commented on src/components/partials/NewPageNavBar/index.js
> +          width={144}
Do you remember conversation from last Friday? Did this not work?
```
const { breakpoints } = useTheme()
const isFirstBreakpoint = useMediaQuery({ max: breakpoints[0] })

<Image layout="fixed" width={isFirstBreakpoint ? SMALL_NUMBER : BIGGER_NUMBER} height={...} />
```

2021-09-28 10:42 UTC, quaardvark commented on src/components/organisms/NewNavBar/AvailRdcNewNavBar/index.js
> +    border: "none",
Not 100% sure, but maybe `borderColor: "transparent"` instead of `border: "none"` will lead to a more aligned sizing here

2021-09-28 10:45 UTC, quaardvark commented
@nshonda please make sure the component matches design spec in it's entirety, including all the dropdowns and popovers. Please reach out to me if you cannot resolve any inconsistencies. This will not be merged unless the component matches design spec

2021-10-01 18:57 UTC, quaardvark approved these changes

2021-10-01 18:59 UTC, merged