Update phone images
rentalutions/marketing pull request #205
Opened 2021-09-30 21:45 UTC by nshonda

Related Issue:
https://airtable.com/appsEN1RgrUk3oyon/tbluJ0kJjMnu1rtsx/viwEjc1BEgM0pj72s/rec5bgyokbgYCcZJK?blocks=hide

2021-09-30 23:15 UTC, quaardvark commented on src/components/partials/SliceZone/components/HowItWorksSlice/index.js
> +              layout="fixed"
This will break a lot of things. Is it necessary?

2021-09-30 23:16 UTC, quaardvark commented on src/components/partials/SliceZone/components/HowItWorksSlice/index.js
> +              layout="fixed"
Just visiting the home page makes it really obvious - https://marketing-git-update-phone-images-rent-avail.vercel.app/

2021-09-30 23:20 UTC, nshonda commented on src/components/partials/SliceZone/components/HowItWorksSlice/index.js
> +              layout="fixed"
sorry, missed this

2021-10-01 08:39 UTC, quaardvark requested changes

2021-10-01 08:39 UTC, quaardvark commented on pages/tenants/digital-leasing/data/second-how-it-works.js
> +          width: 184,
These sizes should match the intrinsic image size

2021-10-01 18:52 UTC, merged