Refactor NavBar to simplify the input required and to facilitate "automatic" responsiveness
rentalutions/marketing pull request #33
Opened 2020-12-21 14:24 UTC by quaardvark

This PR simplifies NavBar in the following ways:

- Removes `push` and `breakpoint` options
- Facilitates "automatic" responsiveness

Introduces the following limitations:

- Only one primary button can exist - the first button with `primary: true`
- Only the primary button will be on the right, `push: true` is no longer supported
- Priority of buttons for responsiveness is simply controlled by their order, - the first button will be hidden last

"Automatic" responsiveness is based on `flex-wrap` and `overflow: hidden`, where buttons wrap out of view when they no longer fit in the box.

2020-12-21 14:58 UTC, henriquecfreitas approved these changes

2020-12-21 14:58 UTC, henriquecfreitas commented on src/components/organisms/NavBar/index.js
> +                : ["flex-end", "flex-end", "flex-end", "flex-start"],
I would suggest to remove those ternaries from the props and to place it before the render function, in order to make the code more clear. If you place it in that `links` `useMemo` callback it would be even better, because the ternary wouldn't be performed on each render, right?

```
const defaultFlexJustifyContent = [ "flex-end", "flex-end", "flex-end", "flex-start" ]
const primaryNavBarButtonDisplay = [ "none", "none", "block" ]
const [ flexJustifyContent, navBarButtonDisplay ] = primaryLink
                  ? [ "flex-start",  primaryNavBarButtonDisplay ]
                  : [ defaultFlexJustifyContent, "block" ]
```
```suggestion
              justifyContent: {flexJustifyContent},
```

2020-12-21 14:58 UTC, henriquecfreitas commented on src/components/organisms/NavBar/index.js
> +                  display={primaryLink ? ["none", "none", "block"] : "block"}
```suggestion
                  display={navBarButtonDisplay}
```

2020-12-21 15:10 UTC, quaardvark commented on src/components/organisms/NavBar/index.js
> +                : ["flex-end", "flex-end", "flex-end", "flex-start"],
I'm not sure if that makes the code clearer. If anything it introduces the gap between declaration and application, which doesn't work at all for CSS. The only real reason to alias CSS properties via variables is for DRY, which is not the case here.

Ternaries are VERY fast, there's no real reason to optimize them.

2020-12-21 21:59 UTC, pkrawc requested changes
I think the overflow hidden thing and a flex-wrap container is really clever. I probably would've opted for calculating the available width with js but your solution seems much more elegant.

We lose the functionality of being able to push a nav item to the right, yeah? The pricing link in the below diagram.
```
[logo] [thing one] [thing two] ------------- [pricing] [primary cta]
```

2020-12-21 21:59 UTC, pkrawc commented on pages/info/[uid].js
> +      target: buttonLink && buttonLink.target,
Is undefined an accepted return for a target? I would think that this should be the following.
```
buttonHash?.replace(/^#/, "") || _self
```

2020-12-21 21:59 UTC, pkrawc commented on src/components/organisms/NavBar/index.js
>    links = [],
Reading through this file I generally think the shape of a link is fairly opaque. It took me a while to grok that there is going to be a `primary` key on one (and only one?) link and we're sorting based on that.

I think just documenting the expected API for links would be good here, so the user doesn't need to understand intrinsically what the shape of the link's Prismic data is.

2020-12-21 21:59 UTC, pkrawc commented on src/components/organisms/NavBar/index.js
> +              height: "48px",
Should probably use the space theme key or `rem`s to make sure this component stays themeable.

2020-12-21 21:59 UTC, pkrawc commented on src/components/organisms/NavBar/index.js
> +              height: "48px",
Again on the pixel values. If pixels are needed we should be utilizing the space key.

2020-12-21 21:59 UTC, pkrawc commented on src/components/organisms/NavBar/index.js
> +                  {...(target && { target, rel: "noopener" })}
Ah, so we're checking for the target here as well. You might be able to remove the duplicate check by just coercing the link props earlier. Maybe this is overkill though, your call.

2020-12-22 17:36 UTC, quaardvark commented on src/components/organisms/NavBar/index.js
>    links = [],
Added some comments to document that

2020-12-22 17:38 UTC, quaardvark commented on pages/info/[uid].js
> +      target: buttonLink && buttonLink.target,
Yeah, it should simply not set `target` and `rel=noopener` and if it's undefined. Can be a jump-link hash

2020-12-22 17:38 UTC, quaardvark commented on src/components/organisms/NavBar/index.js
> +              height: "48px",
Done

2020-12-22 17:38 UTC, quaardvark commented on src/components/organisms/NavBar/index.js
> +              height: "48px",
Done

2020-12-22 17:44 UTC, quaardvark commented on src/components/organisms/NavBar/index.js
> +                  {...(target && { target, rel: "noopener" })}
I moved it into `utils`, since there are few components that use the exact same pattern, so the API is now `{...getTargetProps(target)}` and `getTargetProps` omits `noopener` for `_self` links just in case. I don't really like to mess with `target` and related attributes, since it may have unintended consequences in different browsers, so I prefer to not set anything if `target` is undefined

2020-12-23 12:53 UTC, merged