Creating slider component and testimonials slice
rentalutions/marketing pull request #34
Opened 2020-12-23 22:18 UTC by henriquecfreitas

2020-12-28 11:06 UTC, quaardvark requested changes

2020-12-28 11:06 UTC, quaardvark commented on src/components/molecules/Slider/index.js
> +            return cloneElement(childElement, { ref: refs[idx] })
I get a lot of warnings on missing `key` prop

2020-12-29 18:48 UTC, henriquecfreitas commented on src/components/molecules/Slider/index.js
> +  function calcVisibilityIndexes() {
The scroll function were modified to scroll to the middle of the next/last element that is not fully visible

2020-12-29 18:49 UTC, henriquecfreitas commented on src/components/molecules/Slider/index.js
> +        <ChevronLeft
It is disappearing now, keeping the same height for the controls box that it would have if the buttons were visible

2020-12-29 19:46 UTC, pkrawc commented
Hey guys, sorry I've silent on this. I'm planning on digging tomorrow morning at some point but generally this isn't how I would've gone about creating a carousel. I think we can likely leverage the IntersectionObserver api to get a list of visible items without the need for manual calculation. I think it's totally fair to corner Nellie and lean on her a bit more to illustrate the interactions expected if we're running into a wall on that.

There's no reason to use things like `styled(Box)` since box really doesn't have any default styling and can take any style key in the `sx` prop.

The `Carousel` component is a really good candidate to split out into a hook that controls ui logic and a component that controls style.

```jsx
function useCarousel(props) {
  // return a list of items that should be shown
  // useEffect to check whatever
  return {
    // Carousel Props
  }
}

function Carousel(props, ref) {
  const htmlProps = useCarousel({...props, ref})
  return <Box className="carousel" sx={{/* Carousel Styles */}} />
}
```

2020-12-30 01:25 UTC, pkrawc commented on src/components/organisms/Testimonials/index.js
> +  bg,
Most props should have default values if possible, it's a good way to prevent render errors.

2020-12-30 12:39 UTC, quaardvark commented
@pkrawc are you suggesting to run an IntersectionObserver for each child to detect which are clipping? Would it really be cleaner than calculations?

2020-12-30 13:40 UTC, pkrawc commented
@quaardvark I'm not actually sure. I have a pairing session with @henriquecfreitas this morning to sync up.

I dug more into this slice last night and calculations might be the way to go.

I also wonder if there's more than just scroll position we want to change of the selected testimonial. Which is as much a design thing as an engineering thing.

2020-12-30 13:41 UTC, henriquecfreitas commented
> @pkrawc are you suggesting to run an IntersectionObserver for each child to detect which are clipping? Would it really be cleaner than calculations?

I think is way better now, handling the visibility of the items with a callback for the IntersectionObserver

```
  const [ visibilityIndexes, setVisibilityIndexes ] = useState([])
  const firstVisibleIdx = visibilityIndexes.indexOf(true)
  const lastVisibleIdx = visibilityIndexes.lastIndexOf(true)

  function observerCb(entries) {
    entries.forEach(entry => {
      const index = refs.current.indexOf(entry.target)
      const isVisible = entry.intersectionRatio > VISIBLE_MIN_INTERSECTION
      const updatedVisibilityIndexes = visibilityIndexes
      updatedVisibilityIndexes[index] = isVisible
      setVisibilityIndexes([...updatedVisibilityIndexes])
    })
  }
  useEffect(() => {
    const observer = new IntersectionObserver(observerCb, {
      threshold: VISIBLE_MIN_INTERSECTION,
    })
    refs.current.forEach(ref => observer.observe(ref))
  }, [])
```

2020-12-30 13:45 UTC, pkrawc commented
@henriquecfreitas yeah that's exactly what I was imagining. We should probably set the observer as a ref instead of creating one on ever useEffect call but this is the main gist.

2020-12-30 13:47 UTC, henriquecfreitas commented
> I also wonder if there's more than just scroll position we want to change of the selected testimonial. Which is as much a design thing as an engineering thing.

Maybe applying a scale, like that?
<img width="1172" alt="Screen Shot 2020-12-30 at 10 47 10" src="https://user-images.githubusercontent.com/22528445/103355169-5fea4e80-4a8c-11eb-9b9f-a3be4dda33ae.png">

2020-12-30 14:01 UTC, quaardvark commented
@henriquecfreitas IIRC entries will be given only for updated values when observer callback fires, so you'll need a bit more complex logic to track visibility

2020-12-30 14:17 UTC, quaardvark commented
@pkrawc @henriquecfreitas I'm still not sure on the UX here, - don't we want to track intersection with `Container` and not just `window`? Assuming that the arrows should scroll until either left or right extremes are within the `Container`.

2020-12-30 14:19 UTC, pkrawc commented
Good catch, yeah probably the container. You can set the root element in the options when creating the observer

2020-12-30 14:26 UTC, henriquecfreitas commented
> @pkrawc @henriquecfreitas I'm still not sure on the UX here, - don't we want to track intersection with `Container` and not just `window`? Assuming that the arrows should scroll until either left or right extremes are within the `Container`.

No, I think we need to track the intersection with the Carousel extended view (including the side scroll spaces), not the Container. The windows is working on this case because the carousel 's horizontal view is exactly the same as the window's horizontal view.
 But you're right, it can't be based on the window. I'll set the carousel box as the root view and use the `scrollSpace` prop values as the rootMargin

2020-12-30 14:31 UTC, henriquecfreitas commented
> IIRC entries will be given only for updated values when observer callback fires, so you'll need a bit more complex logic to track visibility

It also fires the callback after the setting the observer for the element, so I can get its initial visibility

2020-12-30 14:55 UTC, quaardvark commented
@pkrawc @henriquecfreitas I can't help but think that these components, calculations, observers are unnecessary complex. I tried to come up with the most simple solution I could think of atm - https://codesandbox.io/s/carousel-v3-kiss-8q3x2?file=/src/index.js

It basically use uses two very simple functions for scrolling:
```
const scrollLeft = () => {
  const leftClipped = childrenRef.current
    .slice()
    .reverse()
    .find(({ offsetLeft, offsetWidth }) => {
      return offsetLeft - scrollRef.current.scrollLeft < 0;
    });
  if (leftClipped) {
    scrollRef.current.scrollTo(leftClipped.offsetLeft, 0);
  }
};

const scrollRight = () => {
  const rightClipped = childrenRef.current.find(
    ({ offsetLeft, offsetWidth }) => {
      return (
        offsetLeft + offsetWidth - scrollRef.current.scrollLeft >
        containerRect.width
      );
    }
  );
  if (rightClipped) {
    scrollRef.current.scrollTo(rightClipped.offsetLeft, 0);
  }
};
```

Not a big fan of left arrow UX, but I think we can tweak it

2020-12-30 15:06 UTC, pkrawc commented
> @pkrawc @henriquecfreitas I can't help but think that these components, calculations, observers are unnecessary complex. I tried to come up with the most simple solution I could think of atm - https://codesandbox.io/s/carousel-v3-kiss-8q3x2?file=/src/index.js
> 
> It basically use uses two very simple functions for scrolling:
> 
> ```
> const scrollLeft = () => {
>   const leftClipped = childrenRef.current
>     .slice()
>     .reverse()
>     .find(({ offsetLeft, offsetWidth }) => {
>       return offsetLeft - scrollRef.current.scrollLeft < 0;
>     });
>   if (leftClipped) {
>     scrollRef.current.scrollTo(leftClipped.offsetLeft, 0);
>   }
> };
> 
> const scrollRight = () => {
>   const rightClipped = childrenRef.current.find(
>     ({ offsetLeft, offsetWidth }) => {
>       return (
>         offsetLeft + offsetWidth - scrollRef.current.scrollLeft >
>         containerRect.width
>       );
>     }
>   );
>   if (rightClipped) {
>     scrollRef.current.scrollTo(rightClipped.offsetLeft, 0);
>   }
> };
> ```
> 
> Not a big fan of left arrow UX, but I think we can tweak it

This is good, observer was a simplification of the manual calculations but I'm liking this more. It's really calling into question the UX of the whole thing for me though.

I don't think the carousel component will be useless but I'm not actually sure if this is the interaction design we should go for. I can't help but think that users are just going to ignore all this text as superfluous, when if we showed them one testimonial at a time it would be more impactful.

2021-01-04 11:14 UTC, quaardvark requested changes

2021-01-04 11:14 UTC, quaardvark commented on src/components/organisms/Testimonials/index.js
> +      opacity: 0.7;
Probably should go as low as 0.2-0.3 for visibility

2021-01-04 11:14 UTC, quaardvark commented on src/components/organisms/Testimonials/index.js
> +      rootMargin: `0px ${scrollSpace}px`,
`rootMargin` should be removed here. It makes it the same as having no root at all, - what's the point then? The idea was to track intersection with `Container` edges. Otherwise this can happen:

![Screenshot_20210104_131045](https://user-images.githubusercontent.com/1927171/103529397-441ce900-4e8e-11eb-8c29-7b02e0cf0aee.png)

Here testimonials are "scrolled" but both buttons are disabled, because there's no intersection with window edges

2021-01-04 11:15 UTC, quaardvark commented on src/components/partials/SliceZone/components/TestimonialsSlice/index.js
> +    <Testimonials
Did we address this? Is skew a CMS option or is it forced skew?

2021-01-04 11:20 UTC, quaardvark commented on .eslintrc
> +    "prefer-arrow-callback": [ "error", { "allowNamedFunctions": true } ],
If we don't use these, let's clean it up. In general, we prefer to override ESLint contextually in the file with `//eslint-disable rule` comments rather that changing the rules. There's no good reason for either of these changes

2021-01-04 13:52 UTC, henriquecfreitas commented on .eslintrc
> +    "prefer-arrow-callback": [ "error", { "allowNamedFunctions": true } ],
I'll remove the `no-plusplus` rule right now.
@pkrawc can you give us a position on the `prefer-arrow-callback` rule?

2021-01-04 14:22 UTC, henriquecfreitas commented on src/components/organisms/Testimonials/index.js
> +      rootMargin: `0px ${scrollSpace}px`,
The buttons are disabled because all the content is visible, it will be enabled when you scroll enough to hide part of the first or the last card. We are tracking intersection with the `Container`, but it has margins on the left and right that need to be passed to the Intersection Observer constructor. Otherwise it would consider only the inner space of the Container, ignoring its margins as visible space

2021-01-04 15:16 UTC, quaardvark commented on src/components/organisms/Testimonials/index.js
> +      rootMargin: `0px ${scrollSpace}px`,
It should consider only the inner space, - that was the idea

2021-01-04 15:52 UTC, pkrawc commented on .eslintrc
> +    "prefer-arrow-callback": [ "error", { "allowNamedFunctions": true } ],
We need to leave the `allowNamedFunctions` boolean as true so that one can write
```jsx
const Comp = forwardRef(function Comp(props, ref) {})
```
If you don't use a function declaration for the inner function then in devtools and stack traces you'll see a lot of `forwardRef: function` instead of `forwardRef: Comp`

2021-01-04 15:53 UTC, pkrawc commented on src/components/organisms/Testimonials/index.js
> +  const [containerObserver, setContainerObserver] = useState()
Agreed here. A couple tutorials have the observer set as state but that's really only important if you want to be notified of changes to the observer itself.

2021-01-04 16:02 UTC, henriquecfreitas commented on src/components/partials/SliceZone/components/TestimonialsSlice/index.js
> +    <Testimonials
On the source it is addressed, but I still need to add the CMS option on prismic

2021-01-04 16:07 UTC, henriquecfreitas commented on src/components/partials/SliceZone/components/TestimonialsSlice/index.js
> +    <Testimonials
I just added it on the CMS, but it is not working, I'm into it right now

2021-01-04 17:42 UTC, henriquecfreitas commented on src/components/organisms/Testimonials/index.js
> +  useEffect(() => {
I didn't understood this one, can you explain it better please?

2021-01-04 18:07 UTC, quaardvark commented on src/components/organisms/Testimonials/index.js
> +  useEffect(() => {
A function returned from `useEffect` is called when the component is being unmounted. It's intended use is to clean up any side effects set up within `useEffect`. We just need to return function that will disconnect the observer, so that it will be recycled properly. Otherwise it can potentially be a memory leak

2021-01-04 18:57 UTC, quaardvark requested changes

2021-01-04 18:57 UTC, quaardvark commented on src/components/organisms/Testimonials/index.js
> +    const last = childrenRef.current.pop()
This mutates the array. A big no-no

2021-01-04 18:57 UTC, quaardvark commented on src/components/organisms/Testimonials/index.js
> +            wrapChildren
Now I understand, `position: relative` is missing here and `offsetLeft` is calculated from `window` which causes all kinds of chaos in calculations.

We need to add `position: relative` and remove `scrollSpace` from calculations of scrolls

2021-01-04 18:57 UTC, quaardvark commented on src/components/organisms/Testimonials/index.js
> +      scrollRef.current.scrollTo(scrollSpace - leftClipped.offsetLeft, 0)
I don't understand the need for `scrollSpace` here

2021-01-04 18:57 UTC, quaardvark commented on src/components/organisms/Testimonials/index.js
> +  }, [scrollSpace, scrollRef.current, childrenRef.current.length])
There should be no need to use `current` and `length` in dependencies here. This hook only really cares about non-stale references to `childrenRef` and `scrollRef`, not their values

2021-01-04 18:57 UTC, quaardvark commented on src/components/organisms/Testimonials/index.js
> +  const scrollLeft = useCallback(() => {
I reworked scrollLeft as such and thought it's a way better solution:
```
const scrollLeft = useCallback(() => {
  const leftClipped = childrenRef.current.find(
    ({ offsetLeft, offsetWidth }) =>
      offsetLeft + offsetWidth - scrollRef.current.scrollLeft >
      0 - containerRect.width
  )
  if (leftClipped) {
    scrollRef.current.scrollTo(leftClipped.offsetLeft, 0)
  }
}, [scrollRef, childrenRef])
```

Bottom line, we want left and right scrolls to scroll approximately same amount

2021-01-04 18:57 UTC, quaardvark commented on src/components/organisms/Testimonials/index.js
> +        <ScrollControlsContainer>
Should these hide when `!mayScrollLeft && !mayScrollRight`?

2021-01-04 18:57 UTC, quaardvark commented on src/components/organisms/Testimonials/testimonials.stories.js
> +export function Default() {
I think it would be good to add a few stories:

1) With 2 cards
2) With 12 cards

2021-01-04 21:11 UTC, pkrawc commented
@henriquecfreitas I just added a small (not exactly working) update to the testimonials layout as a story. It's not a slice and shouldn't affect anything about the slice you're currently building. Tomorrow morning let's go over the update after the stand with Nellie.

2021-01-04 22:35 UTC, henriquecfreitas commented
> @henriquecfreitas I just added a small (not exactly working) update to the testimonials layout as a story. It's not a slice and shouldn't affect anything about the slice you're currently building. Tomorrow morning let's go over the update after the stand with Nellie.

Ok!

2021-01-05 11:56 UTC, quaardvark commented on src/components/organisms/Testimonials/index.js
> +  useEffect(() => {
@henriquecfreitas we should do that. If it's still unclear what needs to be done, - let me know

2021-01-05 11:56 UTC, quaardvark commented
@henriquecfreitas I think the observer cleanup function is still missing, let's add that and we should be good for QA

2021-01-05 15:16 UTC, henriquecfreitas commented on src/components/organisms/Testimonials/index.js
> +  useEffect(() => {
Done!

2021-01-05 15:38 UTC, merged