Add Prismic labels support for RichText, set default heading sizing for components
rentalutions/marketing pull request #36
Opened 2020-12-31 17:20 UTC by quaardvark

**Resolves**

[Airtable - Separate Font Size from Heading](https://airtable.com/tbl4CgbPGPmsSc1pl/viwkpIRDfH7ure4zB/recf0AtqFMUD3zrtn)

**Why**

- Semantic headings hierarchy is important for the SEO, but in practice this hierarchy rarely matches the visual one. This call for separation of semantic H1...H5 from influencing the visual presentation of these headings. In other words, in actual CMS circumstances we might need to have H2 that look like H5

**Solution**

- Set default heading sizing for components/slices that have explicit headings, disregarding the tag itself
- Allow content editors to override default component sizing, as well as default sizing of Rich Text headers via Prismic Labels

**Also Included**

- Switches all headings usage to `<Box as="h{x}" />` to gain acess to `sx`
- Various tweaks and adjustments of spacing
- Switched `babel-eslint` to `@babel/eslint-parser` for optional chaining support, - there are some anecdotes that Babel parser is no longer needed for ESLint, but have no time to verify

**Screenshots**
- Prismic labels
![Screenshot_20201231_191236](https://user-images.githubusercontent.com/1927171/103419544-27399a80-4b9c-11eb-9a99-5a2dd9086107.png)

**Notes**

Regarding Prismic labels format and corresponding config entries: the goal was to make it a bit more idiomatic for CMS users, as well as abstract it a little from the theme / design system specifics, keeping it open for extension.

2021-01-04 15:23 UTC, henriquecfreitas commented on src/components/partials/SliceZone/components/RichText/components/Text/index.js
> +  ${applySx};
This can only be done by creating a styled component? It could not be resolved via props?

2021-01-04 15:28 UTC, henriquecfreitas commented on src/components/partials/SliceZone/components/HowItWorksSlice/index.js
> +    uid: title?.[0]?.text || idx,
Great job on this PR, optional chaining is awesome 😎

2021-01-04 15:32 UTC, henriquecfreitas commented on src/components/partials/SliceZone/components/FrequentlyAskedQuestionsSlice/index.js
> +      eyebrow={eyebrow[0]?.text && <RichText render={eyebrow} />}
Why these properties are passed as arrays? There is any case where it could have more than one element on it?

2021-01-04 15:32 UTC, henriquecfreitas approved these changes

2021-01-04 15:38 UTC, quaardvark commented on src/components/partials/SliceZone/components/RichText/components/Text/index.js
> +  ${applySx};
I guess you could, but why would you? This is the intended way to add `sx` prop support

2021-01-04 15:46 UTC, quaardvark commented on src/components/partials/SliceZone/components/FrequentlyAskedQuestionsSlice/index.js
> +      eyebrow={eyebrow[0]?.text && <RichText render={eyebrow} />}
This is `StructuredText` type in Prismic, it will contain multiple elements for multi-paragraph entries

2021-01-04 15:50 UTC, henriquecfreitas commented on src/components/partials/SliceZone/components/FrequentlyAskedQuestionsSlice/index.js
> +      eyebrow={eyebrow[0]?.text && <RichText render={eyebrow} />}
So shouldn't this possibility be handled here? If `description` gets as a multi-paragraph text, we would be rendering only the first paragraph by accessing only the position `0`?
Think I understood it wrong

2021-01-04 15:56 UTC, pkrawc commented on src/components/partials/SliceZone/components/FrequentlyAskedQuestionsSlice/index.js
> +      eyebrow={eyebrow[0]?.text && <RichText render={eyebrow} />}
He's just checking to make sure at least one item in the array exists.

2021-01-04 15:57 UTC, henriquecfreitas commented on src/components/partials/SliceZone/components/FrequentlyAskedQuestionsSlice/index.js
> +      eyebrow={eyebrow[0]?.text && <RichText render={eyebrow} />}
Oh of course, my bad, sorry

2021-01-04 15:58 UTC, pkrawc commented
@quaardvark So you're proposing allowing the content creator to choose h1..5 as a heading when writing text, but then applying a label that really makes it a different number header?

If that's the case I think it's confusing and we should probably go with the labels named in the design system associated with size and weight, `hero`, `headline`, `title`, `subtitle`, `body--emphasis`, `body`, `small`.

2021-01-04 16:23 UTC, quaardvark commented
@pkrawc The idea is mostly to soft-lock styling of component headings to curated design decisions, disregarding which tag is passed from CMS. So for example, default `PitchCard` has H5 styled headings, but semantically it could/should be H3. So developers task is to ensure that headings are properly styled regardless of H level. In cases where editors need to override that - they can do that by labels. Naturally, this also extends to headings inside RichText, expect their default styling will be our default design system typography, but can also overridden with labels

On terminology, I was going to initially to set them as you suggest, but I thought that it could be very confusing for the CMS users, so I thought to keep it simple. I understand that these styles are not really headers-only and there's an opportunity to make it more generic, but I think we need to consider some middle ground between being meta and being comprehensive for CMS end-users. I also thought, that Typography interface will give an opportunity to abstract some other, more custom styling options to labels (like links, etc). 

Somewhat impactful problem with labels, is that there could only be one label per span, so going with very generic labels is kinda not possible, since we can't compose them.

2021-01-04 18:27 UTC, pkrawc commented
> @pkrawc The idea is mostly to soft-lock styling of component headings to curated design decisions, disregarding which tag is passed from CMS. So for example, default `PitchCard` has H5 styled headings, but semantically it could/should be H3. So the developer's task is to ensure that headings are properly styled regardless of H level. In cases where editors need to override that - they can do that by labels. Naturally, this also extends to headings inside RichText, expect their default styling will be our default design system typography, but can also be overridden with labels
> 
> On terminology, I was going to initially set them as you suggest, but I thought that it could be very confusing for the CMS users, so I thought to keep it simple. I understand that these styles are not really headers-only and there's an opportunity to make it more generic, but I think we need to consider some middle ground between being meta and being comprehensive for CMS end-users. I also thought that the Typography interface will give an opportunity to abstract some other, more custom styling options to labels (like links, etc).
> 
> Somewhat impactful problem with labels is that there could only be one label per span, so going with very generic labels is kinda not possible, since we can't compose them.

Sorry if I'm misunderstanding still, but the desired behavior is to coerce whatever heading that the CMS user chooses into the correct styling for text in the current slice?

I don't think we need labels for that, just use the asText method of the RichText component.

I still think of the labels as class names, and so they don't make much sense to me as h[N]. That seems like bad naming. I would also expect them to function like classes in that there's no point in putting two on a span where the job of both classes is to style the text differently (the one in the later position would override the previous class).

@quaardvark

2021-01-04 18:35 UTC, quaardvark commented
> 
> Sorry if I'm misunderstanding still, but the desired behavior is to coerce whatever heading that the CMS user chooses into the correct styling for text in the current slice?
> 
> I don't think we need labels for that, just use the asText method of the RichText component.

We don't, - we need labels to circumvent this behavior in cases where it's undesirable, so that the editor can still force H3 styling on otherwise H5-like by default component header, should they need to.

> 
> I still think of the labels as class names, and so they don't make much sense to me as h[N]. That seems like bad naming. I would also expect them to function like classes in that there's no point in putting two on a span where the job of both classes is to style the text differently (the one in the later position would override the previous class).
> 

These are not really class names, these are selection option in the dropdown for the CMS users. They are the intended user of labels, not us. Class names can be composed, these don't, so I feel like they could be a bit more specific. 

How would you otherwise propose to name the Heading 5 styling in a way that is not idiosyncratic to the design system and can be understood by external content management staff?

@pkrawc

2021-01-04 18:52 UTC, pkrawc commented
> How would you otherwise propose to name the Heading 5 styling in a way that is not idiosyncratic to the design system and can be understood by external content management staff?

I still think if the CMS user is going to have to learn a list of styling labels for text then we should just use the design system ones yeah? It's not like marketing is totally in the dark about design.avail.co or our brand guidelines. I think idiosyncrasy with the design system is actually probably desired here. KISS would indicate that multiple lists of styles for the dev and CMS user to keep in their heads is a recipe for disaster.

> These are not really class names, these are selection option in the dropdown for the CMS users. They are the intended user of labels, not us. Class names can be composed, these don't, so I feel like they could be a bit more specific.

Class names can be composed, but CSS cascades and overrides so assigning something like the following.
```css
.hero {
  font-size: 4rem;
  font-weight: bold;
}
.title {
  font-size: 3rem;
  font-weight: normal;
}
```
And "composing" them onto an element like `class="hero title"` would still only net you the title's styling.

2021-01-04 19:04 UTC, quaardvark commented
@pkrawc OK, I give up, I was 60:40 on this anyway. We would probably need some editor guide anyway and we can illustrate effects of these labels there.

2021-01-04 21:01 UTC, pkrawc requested changes
Small comments, one of which is just a typo.

2021-01-05 12:23 UTC, quaardvark commented on src/components/organisms/FAQ/faq.stories.js
> +    <React.Fragment>
I actually prefer this way, since it stands out and instantly recognizable. The empty one is not recommended because sometimes you need `key={..}` in those

2021-01-05 12:30 UTC, quaardvark commented
@pkrawc renamed labels to conform with the design system, added `body` and `small` labels as well

2021-01-05 13:35 UTC, pkrawc commented on src/components/organisms/FAQ/faq.stories.js
> +    <React.Fragment>
I don't disagree. I'm all in on using <Fragment/> instead of </> but you were using <React.Fragment/>.

2021-01-05 13:43 UTC, quaardvark commented on src/components/organisms/FAQ/faq.stories.js
> +    <React.Fragment>
Yeah, I prefer `<React.Fragment/>` over `<Fragment/>` for readability. If we want to change that let's enforce it via ESLint in a separate PR, since there are a few places it's used this way.

2021-01-05 15:43 UTC, pkrawc approved these changes
Thanks for these changes @quaardvark.

:shipit:

2021-01-05 15:55 UTC, merged