Add Button/CTA Slice
rentalutions/marketing pull request #37
Opened 2021-01-12 20:20 UTC by henriquecfreitas

Airtable item: https://airtable.com/tbl4CgbPGPmsSc1pl/viwQmvVkCTC16fDO3/recNyoXhzDRPIELtW?blocks=hide

Screenshots:
<img width="821" alt="Screen Shot 2021-01-12 at 2 00 36 PM" src="https://user-images.githubusercontent.com/22528445/104368003-292b2400-54e1-11eb-8bd0-2245b1d81fc0.png">
<img width="466" alt="Screen Shot 2021-01-12 at 2 00 04 PM" src="https://user-images.githubusercontent.com/22528445/104368009-2af4e780-54e1-11eb-8e2f-65a33b479dc1.png">
<img width="879" alt="Screen Shot 2021-01-12 at 1 59 42 PM" src="https://user-images.githubusercontent.com/22528445/104368012-2c261480-54e1-11eb-87c3-ccdf822fa9f0.png">
<img width="1792" alt="Screen Shot 2021-01-12 at 1 59 30 PM" src="https://user-images.githubusercontent.com/22528445/104368018-2cbeab00-54e1-11eb-8acc-5f40fa99d27b.png">
<img width="1791" alt="Screen Shot 2021-01-12 at 1 59 19 PM" src="https://user-images.githubusercontent.com/22528445/104368020-2d574180-54e1-11eb-9c1a-daab3f4896d8.png">
<img width="1792" alt="Screen Shot 2021-01-12 at 1 57 06 PM" src="https://user-images.githubusercontent.com/22528445/104368022-2d574180-54e1-11eb-8db6-8ca494cef1b2.png">
<img width="1791" alt="Screen Shot 2021-01-12 at 1 57 42 PM" src="https://user-images.githubusercontent.com/22528445/104368023-2defd800-54e1-11eb-80e0-0520a6486a50.png">

2021-01-12 23:15 UTC, quaardvark requested changes
Few small things, but also need to see updated `types/info.json`

2021-01-12 23:15 UTC, quaardvark commented on src/components/partials/SliceZone/components/ButtonSlice/index.js
> +const ButtonSlice = ({ slice }) => {
Should probably be called `ButtonCTASlice`? Could you also update content type in `types/info.json`?

2021-01-12 23:15 UTC, quaardvark commented on src/components/organisms/ButtonCTA/index.js
> +  const { flow, textAlign } = useMemo(() => {
I think this is great to implement with styled-system variants API - https://styled-system.com/variants

2021-01-12 23:15 UTC, quaardvark commented on src/components/organisms/ButtonCTA/button.stories.js
> +export default { title: "Components/Testimonials" }
`title` should be "Components/ButtonCTA"

2021-01-12 23:15 UTC, quaardvark commented on src/components/organisms/ButtonCTA/index.js
> +          <RichText
`organisms` shouldn't use `RichtText`, - it should be used in `...Slice`. `RichText` uses Prismic-specific DSL which should not leak into design components

2021-01-12 23:15 UTC, quaardvark commented on src/components/organisms/ButtonCTA/button.stories.js
> +import React from "react"
This storybook doesn't compile for me, because of the above issue with `RichText` being used in design component. Was it tested before opening a PR?

I also think adding a storybook with "No Title" variant would be great

2021-01-13 13:57 UTC, henriquecfreitas commented on src/components/organisms/ButtonCTA/index.js
> +  const { flow, textAlign } = useMemo(() => {
Great! Yes, its definitely better with it.
Thank you

2021-01-13 16:36 UTC, quaardvark requested changes

2021-01-13 16:36 UTC, quaardvark commented on src/types/info.json
> +                  "labels" : {
More of a question, than feedback, - how did you manage to get this structure? Does that mean that we can use different values for name and value?

2021-01-13 16:36 UTC, quaardvark commented on src/components/organisms/ButtonCTA/index.js
> +                background={bg}
It seems like all the attributes after `variant` are unnecessary? I tried to remove them and couldn't see a difference

2021-01-13 16:36 UTC, quaardvark commented on src/components/organisms/ButtonCTA/index.js
> +              <Button
Should use `as="a"` or `forwardedAs="a"` here, since `<button href=` is not a valid HTML, not good for users and SEO.

2021-01-13 16:36 UTC, quaardvark commented on src/components/partials/SliceZone/components/ButtonCTASlice/index.js
> +      buttonText={buttonText}
Could the whole button be implemented here and passed down, like in the other components? Instead of splitting it to text and link, which seems arbitrary. If it needs some specific positioning, it could be wrapped into something in design component.

2021-01-13 16:55 UTC, henriquecfreitas commented on src/types/info.json
> +          "button" : {
Is not, I'll rename it now

2021-01-13 17:00 UTC, henriquecfreitas commented on src/types/info.json
> +                  "labels" : {
I'm not sure about how I got it.
I think this might've been generated by the prismic interface...

Since we're not sure how it works, I'll replace it for the simple array, like in other slices

2021-01-13 17:07 UTC, henriquecfreitas commented on src/components/organisms/ButtonCTA/index.js
> +                background={bg}
The `type` and `display` are unnecessary, I'll remove it.
The `height`, `width` and `margin` attributes are being useful on specific orientations and screen sizes, to keep the button aligned and avoid its growth.
Now I'm not sure about the `textAlign`, but I'll test all of them again now

2021-01-13 17:15 UTC, henriquecfreitas commented on src/components/organisms/ButtonCTA/index.js
> +                background={bg}
`background ` is necessary to make the Button component set the right schema and colors.
Check it [here](https://github.com/rentalutions/marketing/blob/5cb73ebb11f363e435c1303b6634888fa8e683e7/src/components/elements/Button/index.js#L45)

2021-01-13 17:20 UTC, quaardvark commented on src/types/info.json
> +                  "labels" : {
I can't find how to put labels in Prismic UI, that's why I'm asking

2021-01-13 17:24 UTC, quaardvark commented on src/components/organisms/ButtonCTA/index.js
> +                background={bg}
Could we do the positioning via some kind of `<Box/>` instead? I think it would be great if we can allow the parent component to implement the "button". It could be useful for extension, - use some other things in place here.

2021-01-13 17:27 UTC, henriquecfreitas commented on src/components/organisms/ButtonCTA/index.js
> +                background={bg}
Yes, we can implement the Button in the Slice component.
Actually I think we don't even need the `<Box/>`, since we can set the positioning attributes directly on the button component received as prop from the parent, don't we?

2021-01-13 17:33 UTC, henriquecfreitas commented on src/types/info.json
> +                  "labels" : {
Got it...
Unfortunately I don't know how to answer it. This code block was copied from the one I was working on at the Prismic UI

2021-01-13 17:36 UTC, henriquecfreitas commented on src/components/partials/SliceZone/components/ButtonCTASlice/index.js
> +      buttonText={buttonText}
Sure, I'm working on it

2021-01-14 10:21 UTC, quaardvark commented
@henriquecfreitas I cannot see this slice in Prismic anymore. Do you know what happened?

2021-01-14 16:04 UTC, quaardvark approved these changes

2021-01-14 16:12 UTC, merged