Implementing RichText embed content on FAQ Slice
rentalutions/marketing pull request #53
Opened 2021-02-17 22:09 UTC by henriquecfreitas

2021-02-18 14:26 UTC, quaardvark requested changes

2021-02-18 14:26 UTC, quaardvark commented on src/components/partials/SliceZone/components/Embed/index.js
> +  return <RichText {...props} render={[{ type: "embed", oembed: embed }]} />
This should happen vice versa. Rich Text htmlSerializer should render `<Embed />`. We are trying to keep components reasonably vendor-agnostic, which is why we never use RichText in them. RichText is CMS specific code and we should be able to swap it out.

2021-02-18 14:26 UTC, quaardvark commented on src/components/partials/SliceZone/components/FrequentlyAskedQuestionsSlice/index.js
> +        render={styleEmbed(answer, {
This is not a good API. `RichText` props are forwarded to `htmlSerailizer` and you can use them cleaner there, where the actual rendering happens.

2021-02-18 16:22 UTC, henriquecfreitas commented on src/components/partials/SliceZone/components/Embed/index.js
> +  return <RichText {...props} render={[{ type: "embed", oembed: embed }]} />
Yes, I agree, actually this was the first think I thought to do.
But then we would have to handle it on `RichText` to avoid them to be calling each other recursively. Since it would be a bit messing, I preferred to just handle everything on  `RichText` and make `Embed` call it.
But I agree with you, so I'll think of good approach to do it on `Embed` and come back with a solution here

2021-02-18 16:28 UTC, henriquecfreitas commented on src/components/partials/SliceZone/components/Embed/index.js
> +  return <RichText {...props} render={[{ type: "embed", oembed: embed }]} />
Do you agree on this premises?

1. Embed may be called directly from other components, by fields that aren't `RichText`
2. Embed may be called inside `RichText`, from `htmlSerializer`
3. Embed should not call `RichText` anymore, and the `embed` logic that was previously handled by Primic's `RichText` should be done on our `Embed` component now

2021-02-18 16:34 UTC, henriquecfreitas commented on src/components/partials/SliceZone/components/FrequentlyAskedQuestionsSlice/index.js
> +        render={styleEmbed(answer, {
But this style props were meant to be applied only on elements of the type `Embed` inside the RichText.
In this case, I applied it on the video to make it smaller on large screens, since the FAQ `Answer` component should take 100% of the container's width. My intention here was to apply it to the `Embed`, but keeping the `Header` with its original style.
If I use the `RichText` props, they'll be applied to all elements of the `RichText`, including the `Header`. Also, I think that these props wouldn't have priority over the ones that are being handled by `ResponsiveEmbed`.

2021-02-19 12:17 UTC, quaardvark commented on src/components/partials/SliceZone/components/FrequentlyAskedQuestionsSlice/index.js
> +        render={styleEmbed(answer, {
I suggest that we do something like this:
```
<RichText embedSx={{}} />
```

And then in `htmlSerializer`:
```
<Embed
  {...props}
  sx={{
    ...props.sx,
    ...props.embedSx,
  }}
>
```

That way the whole logic with going through the elements and injecting it there can be omitted

2021-02-19 14:33 UTC, henriquecfreitas commented on src/components/partials/SliceZone/components/FrequentlyAskedQuestionsSlice/index.js
> +        render={styleEmbed(answer, {
Great approach, we can go with it.

2021-02-19 14:41 UTC, henriquecfreitas commented on src/components/partials/SliceZone/components/Embed/index.js
> +  return <RichText {...props} render={[{ type: "embed", oembed: embed }]} />
But I don't think that `<Embed />` should be Prismic-specific anymore, considering these proposed changes...
Relying on these premises we may create a reusable and independent component that shouldn't  be affected if we replace Prismic by anything else.

How do you feel about this?

2021-02-19 14:56 UTC, quaardvark commented on src/components/partials/SliceZone/components/Embed/index.js
> +  return <RichText {...props} render={[{ type: "embed", oembed: embed }]} />
It's purpose is to validate that `embed` provider is supported by slices. The actual element-like component is `ResponsiveEmbed`

2021-02-19 17:57 UTC, quaardvark requested changes

2021-02-19 17:57 UTC, quaardvark commented on src/components/elements/ResponsiveEmbed/index.js
> +    <Wrapper sx={{ pb: `${(height / width) * 100}%`, ...sx, ...embedSx }}>
I don't think `embedSx` should be used here? Is it only for a story? Why not just use `sx`?

2021-02-19 17:57 UTC, quaardvark commented on src/components/organisms/FAQ/index.js
> +                            },
This feels out of place here. It takes any elements as an answer and shouldn't really be concerned with embeds. Maybe move it into `<RichText />` in `FaqSlice` and `embedSx` should also be contained to `htmlSerializer`, IMO.

2021-02-23 14:13 UTC, quaardvark approved these changes
:tada:

2021-02-26 13:50 UTC, merged