Fix/testimonials issues
rentalutions/marketing pull request #61
Opened 2021-03-05 12:13 UTC by henriquecfreitas

Resolves #58

2021-03-05 14:25 UTC, quaardvark requested changes
@pkrawc can you elaborate what did you mean by splitting the logic into hooks? Do you envision having them as reusable / standalone components? Or was it just for readability sake?

I any case, I think that we should refrain from declaring them as separate components, - let's just put the files alongside the Testimonials implementation for now. If they will eventually be reusable / standalone components - then we will move them. They are not right now and are just making the components list harder to assess.

2021-03-05 14:25 UTC, quaardvark commented on src/components/elements/LevelEffect/index.js
> +export { default as useLevelEffect } from "./use-level-effect"
Why not put it in the animation utils file we already have? Let's please do that.

2021-03-05 14:25 UTC, quaardvark commented on src/components/molecules/Cards/index.js
> +export { default as CardsControl } from "./cards-control"
Please, let's stop using re-exports. They are pointless and make it harder to trace / jump between implementations. Just import directly from file with implementation. This packages are internal anyway.

Furthermore, I don't understand why we need this as a molecule. Can you envision any other context it's going to be used in this way? I agree with the card visual as a molecule/element, but Cards with the whole logic package? 

Let's please contain the files to the Testimonials organism for now

2021-03-05 14:25 UTC, quaardvark commented on src/components/molecules/Carousel/use-carousel.js
> +import { useCallback, useEffect, useState } from "react"
Same argument applies here, let's contain the hook to the organism

2021-03-05 14:25 UTC, quaardvark commented on src/components/organisms/Testimonials/carousel/testimonials-carousel-item.js
> +  })
Can you explain what was achieved here? I don't see the animations on the preview

2021-03-05 14:33 UTC, henriquecfreitas commented on src/components/elements/LevelEffect/index.js
> +export { default as useLevelEffect } from "./use-level-effect"
Sure!
I also thought that it might be worthy to create an `effects` package on `@rent_avail`

2021-03-05 14:36 UTC, pkrawc commented
> @pkrawc can you elaborate on what did you mean by splitting the logic into hooks? Do you envision having them as reusable/standalone components? Or was it just for readability's sake?

> I any case, I think that we should refrain from declaring them as separate components, - let's just put the files alongside the Testimonials implementation for now. If they will eventually be reusable/standalone components - then we will move them. They are not right now and are just making the components list harder to assess.

Mostly for readability, a little bit for portability. It makes sense to me to house the styling and layout of the component in one file and the rendering logic in another (hook). Eg. the code standards in the readme layout this pattern.

@quaardvark

2021-03-16 14:11 UTC, quaardvark commented
@henriquecfreitas do you know why the build is failing here?

2021-03-17 14:39 UTC, quaardvark commented on src/components/organisms/Testimonials/carousel/testimonials-carousel-item.js
> +  })
@henriquecfreitas Am I testing something wrong? I can't see animation on - https://marketing-git-fix-testimonials-issues-rent-avail.vercel.app/info/listings-dev-test

2021-03-18 14:10 UTC, henriquecfreitas commented
> @henriquecfreitas do you know why the build is failing here?

Wrong export.
Already fixed, thanks!

2021-03-18 18:29 UTC, quaardvark commented on src/components/organisms/Testimonials/carousel/testimonials-carousel-item.js
> +  })
@henriquecfreitas

2021-04-01 09:15 UTC, quaardvark commented on src/components/organisms/Testimonials/carousel/testimonials-carousel-item.js
> +  })
@henriquecfreitas are we planning to address this question?

2021-04-30 19:13 UTC, pkrawc commented
Pretty sure this is stale and doesn't actually need merging, but is there any problem with me doing so? There are no conflicts with staging that I can see.

@henriquecfreitas @quaardvark

2021-05-13 18:22 UTC, henriquecfreitas commented
> Pretty sure this is stale and doesn't actually need merging, but is there any problem with me doing so? There are no conflicts with staging that I can see.
> 
> @henriquecfreitas @quaardvark

Most of the work from this PR is isolating code from `TestimonialsCards` to `useTestimonialsCards`. I wouldn't merge it yet, knowing that this work will be lost as soon as `Slider` gets introduced (bc the logic from `useTestimonialsCards` will be moved to `useSlider` and the slider layout from `TestimonialsCards` will be moved to `Slider`).

I'm already working on the `Slider` component, in order to use it for the Article List component (https://www.figma.com/file/tyf4c9SVsRKSqxTEOyTDkb/?node-id=216%3A0).

The issues related to `TestimonialsCards` will be fixed on that branch. Then we can rebase and rethink this PR in order to address the issues related to `TestimonialsCarousel`. I'll mark this as a WIP and resume working on it as soon as possible.

2021-05-25 17:29 UTC, henriquecfreitas commented
@pkrawc @quaardvark I removed the old commits from this tree since PR #94 already addressed those card/slider related issues (and bc they were very outdated). I left in this PR the changes related to the carousel version (lint fixes and minor adjustments)
Now there isn't much changes left here, but I vote to merge them and close the issue #58

2021-06-03 16:01 UTC, henriquecfreitas commented
I'm closing this PR because all the changes it proposed are being applied by PRs #94 and  #105

2021-06-03 16:01 UTC, closed without merging