Creating Avail/RDC header variant
rentalutions/marketing pull request #68
Opened 2021-03-16 21:16 UTC by henriquecfreitas

2021-03-18 15:56 UTC, quaardvark reviewed
@pkrawc @henriquecfreitas 
Is this misalignment deliberate or accidental?
![Screenshot_20210318_174910](https://user-images.githubusercontent.com/1927171/111655470-59a97a00-8812-11eb-889d-e918c5ef16bb.png)

I don't have a lot of objections. Thanks for making the changes backwards-compatible, but I feel that we can actually ditch the whole "primary: true" option on links and just use the static fields for these. Otherwise the API is too confusing

2021-03-18 15:56 UTC, quaardvark commented on src/types/info.json
> +        "label" : "Primary Button text",
Should be "Secondary Button Text" probably

2021-03-18 15:56 UTC, quaardvark commented on src/types/info.json
> +    },
Are there plans to discontinue NavBar v1? If not, I would prefer to have consistent API, instead of supporting two versions

2021-03-18 15:56 UTC, quaardvark commented on src/components/organisms/NavBar/AvailNavBar/index.js
> +import React from "react"
This component errors out with 
![Screenshot_20210318_173340](https://user-images.githubusercontent.com/1927171/111653029-3c73ac00-8810-11eb-8a5e-51f3a1e5728f.png)

2021-03-18 15:56 UTC, quaardvark commented on pages/info/[uid].js
> +        secondaryButtonHash={secondaryButtonHash}
Can we squash these into objects?

2021-03-18 15:56 UTC, quaardvark commented on src/components/organisms/NavBar/index.js
> +  secondaryButtonHash: sbHash,
Squishy squashy

2021-03-18 16:06 UTC, pkrawc commented
> Is this misalignment deliberate or accidental?
> ![Screenshot_20210318_174910](https://user-images.githubusercontent.com/1927171/111655470-59a97a00-8812-11eb-889d-e918c5ef16bb.png)

What is generating those tracks @quaardvark? Probably yes intended, it looks like an accuratete copy of the codesandbox I proposed.

https://codesandbox.io/s/intelligent-tereshkova-nujdh?file=/src/header.jsx

2021-03-18 16:12 UTC, pkrawc commented on src/components/organisms/NavBar/AvailRdcNavBar/index.js
> +          }}
Why did we choose to use system props instead of the sx object for styling here?

2021-03-18 16:12 UTC, pkrawc commented on src/components/organisms/NavBar/AvailRdcNavBar/index.js
> +              <Menu>
This menu component would do well pulled out of the parent I think

2021-03-18 16:12 UTC, pkrawc commented on src/types/info.json
> +    },
I think this is never going to fully replace all navbars, and I would agree with the consistent API comment.

2021-03-18 16:13 UTC, quaardvark commented
@pkrawc These are just guides I've put in GIMP, no issues on my part if intended

2021-03-18 16:19 UTC, quaardvark commented
@henriquecfreitas also one more thing - the links should support the ID field, just like other standalone buttons

2021-03-18 16:35 UTC, pkrawc commented
Gotcha. Initially, they looked like the grid tracks you get when inspecting a page in chrome or firefox. But yeah layout-wise, seems right to me.

@quaardvark

2021-03-18 16:41 UTC, quaardvark commented on src/components/organisms/NavBar/AvailRdcNavBar/index.js
> +                  as="motion.li"
This cannot be a string, - it will render <motion.li> tag instead of `motion.li` component, - should be `as={motion.li}`

2021-03-18 17:06 UTC, henriquecfreitas commented
> @pkrawc @henriquecfreitas
> Is this misalignment deliberate or accidental?
> ![Screenshot_20210318_174910](https://user-images.githubusercontent.com/1927171/111655470-59a97a00-8812-11eb-889d-e918c5ef16bb.png)

Not intentional. First I tried to keep the same width from the old header, but it was bigger than the mock from code sandbox.
Then I removed the `maxWidth` (that was limited to the container width) and it shrunk  to the right size.
We can place the `maxWidth` back to compare results and choose which one is better.

> I don't have a lot of objections. Thanks for making the changes backwards-compatible, but I feel that we can actually ditch the whole "primary: true" option on links and just use the static fields for these. Otherwise the API is too confusing

Yeah, I would also prefer we use only the static fields, but two things to keep in mind:
1. We'll loose the primary buttons that are current defined by the primary boolean, unless we can migrate that data some way on Prismic.
2. How will we handle the static secondary link fields on the old navbar? There will be no difference from it to the repeatable zone links (but the position?)

2021-03-18 17:11 UTC, henriquecfreitas commented on src/types/info.json
> +    },
Do we want to use the co branded NavBar on all pages?
I'm not sure, but I think I record Matt saying something about using it on specific pages for now.

2021-03-18 17:15 UTC, henriquecfreitas commented on src/types/info.json
> +    },
But I agree @quaardvark, I'm also not 100% comfortable in having so many fields and mainly with having fields with different proposes based on the NavBat Type.

Does it make sense to think about creating a new content type?

2021-03-18 17:17 UTC, henriquecfreitas commented on src/components/organisms/NavBar/AvailRdcNavBar/index.js
> +              <Menu>
Yes it will, good call

2021-03-18 17:22 UTC, henriquecfreitas commented on src/components/organisms/NavBar/AvailRdcNavBar/index.js
> +          }}
I though that declaring them as element props would be better, but no specific reason on that.
I'll place them on `sx`, for this component and others

2021-03-18 17:28 UTC, quaardvark commented
@henriquecfreitas For the layout Patrick says it's OKay.

For the NavBar API - I will just convert old NavBars to new API manually on release, - I don't think we have "secondary" links currently on production pages, so it's mostly about copying "primary" button to new API

2021-03-18 18:04 UTC, henriquecfreitas commented on src/components/organisms/NavBar/AvailNavBar/index.js
> +import React from "react"
I think this was caused by two different links having the same `href`.
This should not happen on production, but maybe we can change the `href` key to a compound key of `text-href`?

2021-03-22 13:18 UTC, quaardvark requested changes

2021-03-22 13:18 UTC, quaardvark commented on src/components/organisms/NavBar/index.js
> +    }
It should be possible to ditch and/or simplify this logic with cutting over from `push: true, primary:true` to explicitly defined primary + secondary buttons

2021-03-22 14:43 UTC, henriquecfreitas commented on src/components/organisms/NavBar/AvailNavBar/index.js
> +  ...props
No.
On the new navbar we have only one secondary button, and the repeatable links are rendered as menu items.
On the old navbar both the static secondary link and all the repeatable links are rendered as secondary buttons, with no differences between them. So we only have to push the secondary link to the `defaultLinks` array.

2021-03-22 14:50 UTC, pkrawc requested changes

2021-03-22 14:50 UTC, pkrawc commented on src/components/organisms/NavBar/AvailRdcNavBar/index.js
> +        display: "flex",
Interesting that background isn't doing what you'd expect.

bg in the sx object should work though.

2021-03-22 16:07 UTC, quaardvark approved these changes

2021-03-23 11:15 UTC, merged