updated pricing page
rentalutions/marketing pull request #73
Opened 2021-03-25 16:22 UTC by KirillTer

2021-03-25 16:39 UTC, quaardvark requested changes

2021-03-25 16:39 UTC, quaardvark commented on pages/info/pricing.js
> +      </Box>
We probably can reuse `PricingTextItem` here. Also because these items clearly need top/bottom margins

2021-03-25 16:39 UTC, quaardvark commented on pages/info/pricing.js
> +    text: "Sing up",
`Sign Up` button should be `primary`

2021-03-25 16:39 UTC, quaardvark commented on pages/info/pricing.js
> +      </Box>
I would ditch `width` and strangely big left margin for these `Box`es, - let it flow naturally.

2021-03-25 16:39 UTC, quaardvark commented on pages/info/pricing.js
> +        <PricingHeaderItem text={'Get the tools for every part of the rental cycle.'} sx={'h3'}/>
Should be `as="h3"` not `sx={'h3'}`

2021-03-25 16:39 UTC, quaardvark commented on pages/info/pricing.js
> +        <PricingTextItem text={'Verified landlord badge and for rent sign.'} />
Would prefer text node to be a child rather then prop -
```
<PricingTextItem>
    Verified landlord badge and for rent sign.
</PricingTextItem>
```

2021-03-25 16:39 UTC, quaardvark commented on pages/info/pricing.js
> +        <PricingHeaderItem text={'Tenants pay for the following:'} sx={'h4'}/>
I think there's a big part of the page missing after this

2021-03-25 16:39 UTC, quaardvark commented on pages/info/pricing.js
> +function planWithButton(p, idx) {
I think this function is unnecessary, let's just put buttons inline to `plans`

2021-03-25 16:39 UTC, quaardvark commented on pages/info/pricing.js
> +  <span>{text}</span>
Prefer `<Text>`

2021-03-25 16:39 UTC, quaardvark commented on pages/info/pricing.js
> +  <Check size="1.3334rem" style={{ marginRight: "1rem" }} />
Prefer `sx` to `style`

2021-03-25 16:39 UTC, quaardvark commented on pages/info/pricing.js
> +const PricingHeaderItem = ({text, sx}) => <Box style={{ margin: "1rem 0 1rem 0" }}>
Prefer `sx` to `style`

2021-03-25 16:39 UTC, quaardvark commented on pages/info/pricing.js
> +      <Box width="24rem" style={{ margin: "0 0 2rem 6rem" }}>
Prefer `sx` to `style`

2021-03-27 16:44 UTC, KirillTer commented on pages/info/pricing.js
> +      </Box>
if we will remove width from item it will break our markup

2021-03-29 11:19 UTC, quaardvark approved these changes

2021-03-29 21:29 UTC, henriquecfreitas requested changes

2021-03-29 21:29 UTC, henriquecfreitas commented on src/components/organisms/PlansPrices/plan-card.js
> -      minWidth: "fit-content",
We shouldn't remove this line. It will cause the layout to break on the `horizontal` orientation

<img width="1248" alt="Screen Shot 2021-03-29 at 4 21 59 PM" src="https://user-images.githubusercontent.com/22528445/112902038-2afd9000-90ab-11eb-9f22-d5f162f1e68d.png">

2021-03-29 21:40 UTC, henriquecfreitas commented on src/components/organisms/PlansPrices/plan-card.js
> -      minWidth: "fit-content",
Also, for the `vertical` orientation, will also cause the layout to break on larger button texts.

2021-03-30 08:12 UTC, quaardvark commented on src/components/organisms/PlansPrices/plan-card.js
> -      minWidth: "fit-content",
This line was causing issues on long texts, - we should fix the component layout to not use `fit-content` horizontally

2021-03-30 10:53 UTC, henriquecfreitas approved these changes

2021-03-30 13:09 UTC, merged